### ISSUE TITLE
can't run example

### ISSUE THREAD

**Issue by AKholetsky** [not-fl3/macroquad#10]
More examples with missed imports.
**tree.rs**
   Compiling macroquad v0.2.0-alpha.0 (E:\Projects\Rust\macroquad)
error[E0433]: failed to resolve: use of undeclared type or module `ScreenCoordinates`
  --> examples\tree.rs:31:28
   |
31 |     set_screen_coordinates(ScreenCoordinates::Fixed(-1., 1., -0.2, 1.4));
   |                            ^^^^^^^^^^^^^^^^^ use of undeclared type or module `ScreenCoordinates`

error[E0425]: cannot find function `set_screen_coordinates` in this scope
  --> examples\tree.rs:31:5
   |
31 |     set_screen_coordinates(ScreenCoordinates::Fixed(-1., 1., -0.2, 1.4));
   |     ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

**life.rs**
   Compiling macroquad v0.2.0-alpha.0 (E:\Projects\Rust\macroquad)
error[E0432]: unresolved imports `macroquad::set_screen_coordinates`, `macroquad::ScreenCoordinates`
 --> examples\life.rs:3:19
  |
3 |     screen_width, set_screen_coordinates, update_texture, Image, ScreenCoordinates, BLACK, WHITE,
  |                   ^^^^^^^^^^^^^^^^^^^^^^                         ^^^^^^^^^^^^^^^^^ no `ScreenCoordinates` in the root
  |                   |
  |                   no `set_screen_coordinates` in the root

**Comment by not-fl3** [comment]
fixed, thank for report
