### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by urbainy** [not-fl3/macroquad#100]
Sorry, I just began to use Rust for a short while. And I am trying to use your lib.
I work on Linux. I create a new project by "cargo new ... " command. I put "macroquad = "0.2.9" in the Cargo.toml. And I copied your example folder's code into mine. But from the very beginning, I received a lot of error by the compiler. Such as "can not find prelude", "can not find Conf" and etc.
I don't know what I should do. Thanks for help!

**Comment by ozkriff** [comment]
This doesn't sound like an issue specific to macroquad and would most likely hard to debug in github issue - consider asking about it in [the Game Development in Rust Discord server](https://discord.gg/yNtPTb2).

**Comment by not-fl3** [comment]
Examples in the git repo are from `0.3.0-alpha` version. 

You can use it with `macroqud = "0.3.0-alpha"` in your Cargo.toml file.

**Comment by urbainy** [comment]
Many thanks!
