### ISSUE TITLE
3d.exe example binary doesn't work

### ISSUE THREAD

**Issue by adsick** [not-fl3/macroquad#105]
When I do `cargo run --example 3d` works fine, but when I try to run actuall 3d.exe from target dir, two windows pop up and instantly close.
At this moment I saw it only with 3d example, but I didn't tried all. Tree and asteroids are working fine.

**Comment by not-fl3** [comment]
Asset paths are relative to the current working folder. 
So you should either put your assets next to the .exe file or run it from the folder containing the assets
