### ISSUE TITLE
Consider adding a LICENSE file

### ISSUE THREAD

**Issue by cata0309** [not-fl3/macroquad#110]
Hello!
Could you add a license to this project? Unlicensed code is actually a not so happy code, read: https://choosealicense.com/no-permission/.
People should know what they are allowed to do when using this project!
Thank you!

**Comment by not-fl3** [comment]
Good point, will add! 

However, the license is in the Cargo.toml and on crates.io, which makes macroquad's code licensed.

**Comment by not-fl3** [comment]
Added license files to the repo root as well. 
https://github.com/not-fl3/macroquad/pull/111
