### ISSUE TITLE
Dependency Exists on Relative-Path version of MegaUI

### ISSUE THREAD

**Issue by JosephCatrambone** [not-fl3/macroquad#12]
The Cargo.toml file currently has a dependency on a copy of megaui in ../megaui.  Prevents running or building with macroquad.

**Comment by not-fl3** [comment]
Cargo uses local paths only for local builds, when macroquad is used either from git or cargo - local paths are ignored. 
But apparently this does not really help for building examples locally, so will remove `path = ` soon!

**Comment by not-fl3** [comment]
Fixed on master, thanks for report!
