### ISSUE TITLE
How to Get Context In Macroquad

### ISSUE THREAD

**Issue by Pebaz** [not-fl3/macroquad#128]
I'd like to set the filter mode for a texture:

```rust
texture.set_filter(&mut get_context(), FilterMode::Nearest);
```

Unfortunately, the [get_context()](https://github.com/not-fl3/macroquad/blob/1ce46bacb4d91c42e979a359b050d4d8a8d88dd4/src/lib.rs#L178) function is private. How do I get the current context in order to use the functions that require it?

**Comment by not-fl3** [comment]
there is `texture::set_filter_mode` function without a context, 

`Texture2D::set_filter` in a public api is a bug and will be removed

**Comment by Pebaz** [comment]
Awesome, thanks!
