### ISSUE TITLE
Constrain Mouse To Window (For First Person Camera infinite mouse scrolling)

### ISSUE THREAD

**Issue by Pebaz** [not-fl3/macroquad#129]
I'm trying to get a first person 3D camera to work. Currently, I can successfully fly around the world and look using the mouse.

However, when the mouse reaches the edge of the screen, it hits the edge and no longer gives any mouse position information.

There are 2 ways to solve this that I can see:

1. Keep sending mouse events when mouse is outside the window.
2. Allow the user to set the mouse position so they can control wrapping the mouse when it goes outside the window.

I don't know if Sokol uses GLFW but in Raylib (GLFW), I have this same problem on Linux. Not quite sure how to solve it without a way to set the cursor position.

Note: I have used the `ctx.set_cursor_grab(true)` and `ctx.show_mouse(false)` functions and it doesn't change the above behavior.

Alternatively, if another 3D example could be created that tests the mouse look and screen border interaction that would be amazing.

Here is what I've got so far for reference:

```rust
use macroquad::prelude::*;
// use glam::vec3;

const MOVE_SPEED: f32 = 0.1;
const LOOK_SPEED: f32 = 0.1;


fn conf() -> Conf
{
    Conf {
        window_title: String::from("Macroquad"),
        window_width: 1260,
        window_height: 768,
        fullscreen: true,
        ..Default::default()
    }
}

#[macroquad::main(conf)]
async fn main() {
    let InternalGlContext { quad_context: ctx, ..} = unsafe { get_internal_gl() };

    ctx.show_mouse(false);
    ctx.set_cursor_grab(true);

    let dirt = load_texture("Dirt.png").await;
    dirt.set_filter(ctx, FilterMode::Nearest);

    let mut x = 0.0;
    let mut switch = false;
    let bounds = 8.0;


    let world_up = vec3(0.0, 1.0, 0.0);
    let mut yaw: f32 = 0.0;
    let mut pitch: f32 = 0.0;

    let mut facing = vec3(
        yaw.cos() * 1.0,
        0.0,
        yaw.sin() * 1.0
    ).normalize();

    let mut front = vec3(
        yaw.cos() * pitch.cos(),
        pitch.sin(),
        yaw.sin() * pitch.cos()
    ).normalize();
    let mut right = front.cross(world_up).normalize();
    let mut up;

    let mut position = vec3(0.0, 1.0, 0.0);
    let mut last_mouse_position: Vec2 = mouse_position().into();

    let mut own_mouse_position = vec2(0.0, 0.0);

    loop {
        let delta = get_frame_time();
        
        if is_key_pressed(KeyCode::Escape) { break; }

        if is_key_down(KeyCode::Up) { position += front * MOVE_SPEED; }
        if is_key_down(KeyCode::Down) { position -= front * MOVE_SPEED; }
        if is_key_down(KeyCode::Left) { position -= right * MOVE_SPEED; }
        if is_key_down(KeyCode::Right) { position += right * MOVE_SPEED; }

        let mouse_position: Vec2 = mouse_position().into();
        let mouse_delta = mouse_position - last_mouse_position;
        last_mouse_position = mouse_position;

        yaw += mouse_delta.x * delta * LOOK_SPEED;
        pitch += mouse_delta.y * delta * -LOOK_SPEED;

        pitch = if pitch > 1.5 { 1.5 } else { pitch };
        pitch = if pitch < -1.5 { -1.5 } else { pitch };

        facing = vec3(
            yaw.cos() * 1.0,
            0.0,
            yaw.sin() * 1.0
        ).normalize();
    
        front = vec3(
            yaw.cos() * pitch.cos(),
            pitch.sin(),
            yaw.sin() * pitch.cos()
        ).normalize();

        right = front.cross(world_up).normalize();
        up = right.cross(front).normalize();


        x += if switch { 0.04 } else { -0.04 };
        if x >= bounds || x <= -bounds { switch = !switch; }

        clear_background(Color::new(1.0, 0.7, 0.0, 1.0));

        // Going 3d!

        set_camera(Camera3D {
            position: position,
            up: up,
            target: position + front,
            ..Default::default()
        });

        draw_grid(20, 1.);

        draw_line_3d(vec3(x, 0.0, x), vec3(5.0, 5.0, 5.0), Color::new(1.0, 1.0, 0.0, 1.0));

        draw_cube_wires(vec3(0., 1., -6.), vec3(2., 2., 2.), DARKGREEN);
        draw_cube_wires(vec3(0., 1., 6.), vec3(2., 2., 2.), DARKBLUE);
        draw_cube_wires(vec3(2., 1., 2.), vec3(2., 2., 2.), YELLOW);

        draw_cube(vec3(x, 1., x), vec3(2., 2., 2.), dirt, WHITE);

        // Back to screen space, render some text

        set_default_camera();
        draw_text("WELCOME TO 3D WORLD", 10.0, 20.0, 30.0, BLACK);

        draw_text(format!("X: {} Y: {}", own_mouse_position.x, own_mouse_position.y).as_str(), 10.0, 48.0, 30.0, BLACK);
        draw_text(format!("X: {} Y: {}", mouse_position.x, mouse_position.y).as_str(), 10.0, 48.0 + 18.0, 30.0, BLACK);

        next_frame().await
    }
}
```

**Comment by Pebaz** [comment]
I had a chance to test the WASM version of this and the mouse behaves exactly the same.

The calls to grab the mouse and hide it also seem to not have any affect.

**Comment by Pebaz** [comment]
@not-fl3 Was able to test this on Windows also and it had the same effect.

I guess the root question here is: how do I lock the user's cursor to the window using Macroquad (only) or Miniquad context?

**Comment by Pebaz** [comment]
@not-fl3 Ah, that explains it: https://github.com/not-fl3/miniquad/issues/139

It looks like cursor grabbing and relative mouse coordinates is not implemented for Windows. :/

As my game is targeting Windows and needs a working FPS camera, this is a necessary feature for me.

**Comment by not-fl3** [comment]
This was fixed on miniquad 0.3.0-alpha.26: https://github.com/not-fl3/miniquad/pull/164/files

There was a FPS example based on this PR and it worked fine.

**Comment by Pebaz** [comment]
This is good! I ran the FPS example on WASM and Windows and both worked as expected.

However, it seems that I am already depending on a version of Macroquad that depends on Miniquad v0.3.0-alpha.26:

```toml
[dependencies]
macroquad = { git = "https://github.com/not-fl3/macroquad" }
glam = "*"
```

In my `Cargo.lock`:

```toml
[[package]]
name = "macroquad"
version = "0.3.0-alpha.14"
source = "git+https://github.com/not-fl3/macroquad#1ce46bacb4d91c42e979a359b050d4d8a8d88dd4"
dependencies = [
 "bumpalo",
 "fontdue",
 "glam 0.10.2",
 "image",
 "macroquad_macro",
 "miniquad",
 "quad-rand",
]

[[package]]
name = "macroquad_macro"
version = "0.1.2"
source = "git+https://github.com/not-fl3/macroquad#1ce46bacb4d91c42e979a359b050d4d8a8d88dd4"

[[package]]
name = "miniquad"
version = "0.3.0-alpha.26"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2f93dc8b526b2d565063e819449f0e2e7d6acfbf638c9a14c017d5f6c57e3caf"
dependencies = [
 "sapp-android",
 "sapp-darwin",
 "sapp-dummy",
 "sapp-ios",
 "sapp-linux",
 "sapp-wasm",
 "sapp-windows",
] 
```

**Comment by Pebaz** [comment]
Modified the [raw_miniquad](https://github.com/not-fl3/macroquad/blob/master/examples/raw_miniquad.rs) example to make the `set_cursor_grab()` and `show_mouse()` calls but it also did not work. Still using the same Cargo configuration.

**Comment by Pebaz** [comment]
https://user-images.githubusercontent.com/28033767/105640935-24566080-5e4f-11eb-8e4d-c49cef76479a.mp4

Here is a video of it in action. The mouse X coordinate never goes beyond around 790 because tracking stops when it leaves the window.

**Comment by Pebaz** [comment]
Interesting thing to note, the MiniFPS example is using miniquad 0.3.0-alpha.25 not 0.3.0-alpha.26 which is what I'm using.

**Comment by not-fl3** [comment]
Macroquad's mouse_position do not support raw mouse input events yet. 
So for now macroquad do not support what you want unfortunately :(

**Comment by Pebaz** [comment]
Ah, thank you for the quick reply. I will use Miniquad directly while raw mouse input events are being implemented in Macroquad!

Thank you for all your help :)

**Comment by Pebaz** [comment]
I have had no less than 3 situations recently where I would have opted to use Macroquad (aside from my main project), but because it doesn't support raw mouse input events yet I was unable to.

I'd really like to use Macroquad with it's much simpler API for quick projects and really need this feature. Although I am content with using Microquad for my main project for now, I'd really like to make quicker, smaller games in Macroquad.

**Comment by not-fl3** [comment]
Eventually, I will do it, thanks for the feedback!

But meanwhile PRs with this would always be appreciated :)

**Comment by Pebaz** [comment]
This is great to hear!

In theory, if I had the prerequisite skills to do so and the time, could you outline the rough steps I'd need to add this feature? :)

**Comment by not-fl3** [comment]
Yeah, it should be pretty simple

I would make an API call that will grab the cursor and will set some bool flag that the cursor is grabbed and now raw events should be read
And when that bool is set I'll feed mouse_delta data with raw events instead of normal ones
