### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by AKholetsky** [not-fl3/macroquad#13]
$ cargo build
   Compiling autocfg v1.0.0
   Compiling byteorder v1.3.4
   Compiling cfg-if v0.1.10
   Compiling adler32 v1.0.4
   Compiling cc v1.0.50
   Compiling libc v0.2.68
   Compiling crc32fast v1.2.0
   Compiling bitflags v1.2.1
   Compiling macroquad_macro v0.1.0 (E:\Projects\Rust\macroquad\macroquad_macro)
   Compiling quad-rand v0.1.1
   Compiling glam v0.8.6
   Compiling num-traits v0.2.11
   Compiling num-integer v0.1.42
   Compiling num-rational v0.2.4
   Compiling num-iter v0.1.40
   Compiling inflate v0.4.5
   Compiling sapp-windows v0.2.8
   Compiling stb_truetype v0.3.1
   Compiling deflate v0.7.20
   Compiling ordered-float v1.0.2
   Compiling approx v0.3.2
   Compiling png v0.15.3
   Compiling rusttype v0.8.3
   Compiling miniquad v0.3.0-alpha.5
error[E0425]: cannot find function `glPixelStorei` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics\texture.rs:151:13
    |
151 |             glPixelStorei(GL_UNPACK_ALIGNMENT, 1); // miniquad always uses row alignment of 1
    |             ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `GL_UNPACK_ALIGNMENT` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics\texture.rs:151:27
    |
151 |             glPixelStorei(GL_UNPACK_ALIGNMENT, 1); // miniquad always uses row alignment of 1
    |                           ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `GL_TEXTURE_SWIZZLE_A` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics\texture.rs:158:52
    |
158 |                     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_SWIZZLE_A, GL_RED as _);
    |                                                    ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `GL_TEXTURE_SWIZZLE_A` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics\texture.rs:161:52
    |
161 |                     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_SWIZZLE_A, GL_ALPHA as _);
    |                                                    ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `GL_ALPHA` in this scope
    --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics\texture.rs:161:74
     |
161  |                     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_SWIZZLE_A, GL_ALPHA as _);
     |                                                                          ^^^^^^^^ help: a constant with a similar name exists: `C1_ALPHA`
     |
    ::: C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\sapp-windows-0.2.8\src\sokol_app_msvc.rs:6775:1
     |
6775 | pub const C1_ALPHA: u32 = 256;
     | ------------------------------ similarly named constant `C1_ALPHA` defined here

error[E0425]: cannot find function `glPixelStorei` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics\texture.rs:290:13
    |
290 |             glPixelStorei(GL_UNPACK_ALIGNMENT, 1); // miniquad always uses row alignment of 1
    |             ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `GL_UNPACK_ALIGNMENT` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics\texture.rs:290:27
    |
290 |             glPixelStorei(GL_UNPACK_ALIGNMENT, 1); // miniquad always uses row alignment of 1
    |                           ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `GL_TEXTURE_SWIZZLE_A` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics\texture.rs:297:52
    |
297 |                     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_SWIZZLE_A, GL_RED as _);
    |                                                    ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `GL_TEXTURE_SWIZZLE_A` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics\texture.rs:300:52
    |
300 |                     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_SWIZZLE_A, GL_ALPHA as _);
    |                                                    ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `GL_ALPHA` in this scope
    --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics\texture.rs:300:74
     |
300  |                     glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_SWIZZLE_A, GL_ALPHA as _);
     |                                                                          ^^^^^^^^ help: a constant with a similar name exists: `C1_ALPHA`
     |
    ::: C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\sapp-windows-0.2.8\src\sokol_app_msvc.rs:6775:1
     |
6775 | pub const C1_ALPHA: u32 = 256;
     | ------------------------------ similarly named constant `C1_ALPHA` defined here

error[E0425]: cannot find function `glDeleteFramebuffers` in this scope
     --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics.rs:568:18
      |
568   |         unsafe { glDeleteFramebuffers(1, &mut render_pass.gl_fb as *mut _) }
      |                  ^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `glGenFramebuffers`
      |
     ::: C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\sapp-windows-0.2.8\src\sokol_app_msvc.rs:41804:5
      |
41804 |     pub fn glGenFramebuffers(n: GLsizei, framebuffers: *mut GLuint);
      |     ---------------------------------------------------------------- similarly named function `glGenFramebuffers` defined here

error[E0425]: cannot find function `glFrontFace` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics.rs:669:21
    |
669 |                     glFrontFace(GL_CW);
    |                     ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `glFrontFace` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics.rs:672:21
    |
672 |                     glFrontFace(GL_CCW);
    |                     ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `glCullFace` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics.rs:698:17
    |
698 |                 glCullFace(GL_FRONT);
    |                 ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `glCullFace` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics.rs:702:17
    |
702 |                 glCullFace(GL_BACK);
    |                 ^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `glStencilOpSeparate` in this scope
     --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics.rs:773:17
      |
773   |                 glStencilOpSeparate(
      |                 ^^^^^^^^^^^^^^^^^^^ help: a static with a similar name exists: `_sapp_glStencilOpSeparate`
      |
     ::: C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\sapp-windows-0.2.8\src\sokol_app_msvc.rs:41977:5
      |
41977 |     pub static mut _sapp_glStencilOpSeparate: PFN_glStencilOpSeparate;
      |     ------------------------------------------------------------------ similarly named static `_sapp_glStencilOpSeparate` defined here

error[E0425]: cannot find function `glStencilFuncSeparate` in this scope
     --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics.rs:779:17
      |
779   |                   glStencilFuncSeparate(
      |                   ^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `glBlendFuncSeparate`
      |
     ::: C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\sapp-windows-0.2.8\src\sokol_app_msvc.rs:42468:5
      |
42468 | /     pub fn glBlendFuncSeparate(
42469 | |         sfactorRGB: GLenum,
42470 | |         dfactorRGB: GLenum,
42471 | |         sfactorAlpha: GLenum,
42472 | |         dfactorAlpha: GLenum,
42473 | |     );
      | |______- similarly named function `glBlendFuncSeparate` defined here

error[E0425]: cannot find function `glStencilMaskSeparate` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics.rs:785:17
    |
785 |                 glStencilMaskSeparate(GL_FRONT, front.write_mask);
    |                 ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `glStencilOpSeparate` in this scope
     --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics.rs:788:17
      |
788   |                 glStencilOpSeparate(
      |                 ^^^^^^^^^^^^^^^^^^^ help: a static with a similar name exists: `_sapp_glStencilOpSeparate`
      |
     ::: C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\sapp-windows-0.2.8\src\sokol_app_msvc.rs:41977:5
      |
41977 |     pub static mut _sapp_glStencilOpSeparate: PFN_glStencilOpSeparate;
      |     ------------------------------------------------------------------ similarly named static `_sapp_glStencilOpSeparate` defined here

error[E0425]: cannot find function `glStencilFuncSeparate` in this scope
     --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics.rs:794:17
      |
794   |                   glStencilFuncSeparate(
      |                   ^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `glBlendFuncSeparate`
      |
     ::: C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\sapp-windows-0.2.8\src\sokol_app_msvc.rs:42468:5
      |
42468 | /     pub fn glBlendFuncSeparate(
42469 | |         sfactorRGB: GLenum,
42470 | |         dfactorRGB: GLenum,
42471 | |         sfactorAlpha: GLenum,
42472 | |         dfactorAlpha: GLenum,
42473 | |     );
      | |______- similarly named function `glBlendFuncSeparate` defined here

error[E0425]: cannot find function `glStencilMaskSeparate` in this scope
   --> C:\Users\mam0nten0k\.cargo\registry\src\github.com-1ecc6299db9ec823\miniquad-0.3.0-alpha.5\src\graphics.rs:800:17
    |
800 |                 glStencilMaskSeparate(GL_BACK, back.write_mask);
    |                 ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 21 previous errors

For more information about this error, try `rustc --explain E0425`.
error: could not compile `miniquad`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by not-fl3** [comment]
Fixed, thanks for report!
