### ISSUE TITLE
Problem building WASM

### ISSUE THREAD

**Issue by boymaas** [not-fl3/macroquad#14]
Looking into using macroquad for a WASM prototype. For some reason the WASM build seems to be failing on a missing import. 

![image](https://user-images.githubusercontent.com/300333/83950193-1ce33800-a829-11ea-8afc-3f483d2ddca7.png)

Just following the documentation, and double checked everything. gl.js which is placed online maybe outdated?

Great work on the implementation, and fundamental choices.

**Comment by not-fl3** [comment]
Yes, it was outdated. Updated!

**Comment by not-fl3** [comment]
Until this PR https://github.com/not-fl3/miniquad/pull/97 will be merged the best way to use gl.js is

- host appropriate gl.js from https://github.com/not-fl3/miniquad/blob/master/native/sapp-wasm/js/gl.js alongside with .wasm
- depend on specific gl.js version hosted with miniquad-samples
right now it is: 
```
 <script src="https://not-fl3.github.io/miniquad-samples/gl-0.1.17.js"></script>
 <script>load("arkanoid.wasm");</script>
```

**Comment by boymaas** [comment]
Thank you! The master version of gl.js is still missing the "time" function. Made it work by hosting it next to the .wasm and adding a temporary noop time function like this.

![image](https://user-images.githubusercontent.com/300333/83950652-b06a3800-a82c-11ea-8080-156253558cfa.png)

**Comment by not-fl3** [comment]
hmm, this is weird, `time` function should not be required! 
https://not-fl3.github.io/miniquad-samples/gl-0.1.17.js do not have `time` as well and everything works. 

Did you tried `cargo update` on you macroquad project?

**Comment by boymaas** [comment]
I am using this version: `macroquad = "0.1.4"`. Should I be using the `0.2.0-alpha.7`?

**Comment by not-fl3** [comment]
I guess for "0.1.4" you need `https://not-fl3.github.io/miniquad-samples/gl-0.2.54.js` 

But highly recommend updating to `0.2.0-alpha.7`, `0.1.4` is quite an old version!

**Comment by boymaas** [comment]
Thank you for the information, will do an update and check how everything works
