### ISSUE TITLE
Camera2D Help

### ISSUE THREAD

**Issue by Pebaz** [not-fl3/macroquad#147]
I am trying to use Camera2D, but it results in a vertically-flipped extremely zoomed in render:

```rust
set_camera(Camera2D {
    target: vec2(0.0, 0.0),
    zoom: vec2(1.0, 1.0),  // Using 0.0, 0.0 doesn't work either. Values such as (0.005, 0.005) work, but don't make sense?
    offset: vec2(0.0, 0.0),
    rotation: 0.0,
    ..Default::default()
});
```

![image](https://user-images.githubusercontent.com/28033767/107155806-72d42680-6948-11eb-8f92-8ced992eeaf8.png)

What is the correct way to use Camera2D? I don't really need to zoom, but it would be nice to experiment with it. I'm just trying to get a simple XY camera offset going.

**Comment by not-fl3** [comment]
To vertically flip you can use `zoom: vec2(1.0, -1.0)`

For nicer way to setup camera you can use Camera2D::from_display_rect(Rect::(x, y, w, y))

**Comment by Pebaz** [comment]
That's exactly what I needed! Thanks! 😀
