### ISSUE TITLE
Can't figure out how to access the document when running in WASM…

### ISSUE THREAD

**Issue by bwinton** [not-fl3/macroquad#148]
So… I've got some code, and when I run it as an app, I can use `clap` to get arguments, but when I use WASM, (which builds just fine with `cargo build --release --target=wasm32-unknown-unknown && 
cp target/wasm32-unknown-unknown/release/mazes.wasm static && 
basic-http-server static`) I'd like to get the `document.location.search` field for the arguments.

But if I try to get to it using the `web_sys` or `wasm_bindgen` crates (behind the requisite `#[cfg(target_arch = "wasm32")]
`), I get error messages in the browser console:
```
No __wbindgen_describe function in gl.js gl.js:1:26892
No __wbindgen_throw function in gl.js gl.js:1:26892
No __wbindgen_externref_table_grow function in gl.js gl.js:1:26892
No __wbindgen_externref_table_set_null function in gl.js
```

Is there any way to get to the document.location? Other places I've seen suggest using `wasm-bindgen`, which looks like it might do a bunch of the same stuff as `gl.js` does, but I'm not sure how to get that working, or if it's a good idea.

**Comment by not-fl3** [comment]
You can make a js plugin accessing `document.location.search`. For plugins references check https://github.com/not-fl3/miniquad/wiki/JavaScript-interop
There was(probably outdated) implementation doing exactly this https://github.com/optozorax/miniquad-parameters

Also for reference on how to pass strings between rust and js etc you can take a look at https://github.com/not-fl3/quad-net/blob/master/src/client/websocket.rs

**Comment by bwinton** [comment]
That makes sense, thanks! For a more general solution, how hard do you think it would be to make a plugin that exposed all the web_sys stuff (or just the glue code that wasm_bindgen creates)?

**Comment by not-fl3** [comment]
While miniquad do not use either stdweb or wasm-bindgen it is definitely possible to use it with both tools. 
I guess it would involve using their generated JS and miniquad's JSs alltogether.  

However I never did it myself and can't really recommend doing it - it may be too complicated on the stdweb/wasm-bindgen side.

Recommended way to interop with JS - is the one from the links I posted :)

**Comment by bwinton** [comment]
I realize now that I forgot to loop back on this and say "[It works!](https://bwinton.github.io/mazes/?hexparallel)" 🙂

(And I've run into a couple of other weird bugs, which I'll file when I get some spare time…)

Thanks!
