### ISSUE TITLE
Would love it when `draw_text` would return dimensions of what has been written

### ISSUE THREAD

**Issue by boymaas** [not-fl3/macroquad#15]
Especially when using draw_text in a context where you need to center or place it dynamically.

**Comment by mlambir** [comment]
Hey, hadn't seen this issue, but In #16 I added a "measure_text" function, that gives you the expected size for a text, before it's drawn. (heavily inspired in raylib's MeasureText function)

**Comment by boymaas** [comment]
Wonderful! Thank you for the info, just what I was looking for
