### ISSUE TITLE
Shapes don't display on MacOS until the window is resized.

### ISSUE THREAD

**Issue by bwinton** [not-fl3/macroquad#154]
Reproducable with the `basic_shapes.rs` example file. All I see is red, until I resize the window, and then stuff starts to show up. (Also shows up in some code I wrote. Windows and WASM are fine, though. 🙂)

MacBook Pro (15-inch, 2018), macOS 11.2.2 (20D80), Radeon Pro 560X 4 GB, if that matters…

**Comment by not-fl3** [comment]
What macroquad version are you on?

**Comment by bwinton** [comment]
I had just tried it with the latest code from github when I filed the report, but have been noticing it since I started looking at the library 25-ish days ago.

**Comment by TidyMaze** [comment]
Same issue here with `macroquad="0.3.0-alpha.15"`, on `MacBookPro14,2` `Retina 2560 × 1600`

I noticed
```
    let height = screen_height() as u32;
    let width = screen_width() as u32;

    println!("{} {}", height, width);
```

gives `1200 1600` instead of `1600 2560`, not sure if it's related

**Comment by not-fl3** [comment]
I believe this is fixed
