### ISSUE TITLE
screen_width/height wrong before resize

### ISSUE THREAD

**Issue by extrawurst** [not-fl3/macroquad#177]
easiest to see in the camera example (note the debug logging for the screen size I added)
```
use macroquad::prelude::*;

#[macroquad::main("Camera")]
async fn main() {
    loop {
        clear_background(RED);

        // Render some primitives in camera space

        debug!("size: {},{}",screen_width() ,screen_height());

        set_camera(Camera2D {
            zoom: vec2(1., screen_width() / screen_height()),
            ..Default::default()
        });
        draw_line(-0.4, 0.4, -0.8, 0.9, 0.05, BLUE);
        draw_rectangle(-0.3, 0.3, 0.2, 0.2, GREEN);
        draw_circle(0., 0., 0.1, YELLOW);

        // Back to screen space, render some text

        set_default_camera();
        draw_text("HELLO", 30.0, 200.0, 30.0, BLACK);

        next_frame().await
    }
}
```

leads to this output:
```
size: 1600,1200
size: 1600,1200
size: 1600,1200
size: 1600,1200
size: 1600,1200
size: 1600,1200
size: 1600,1200
size: 1600,1200
resize_event: 807,606
size: 807,606
....
```

the window looks like this before I resize (this is not 1600x1200):
<img width="912" alt="image" src="https://user-images.githubusercontent.com/776816/112071693-9fe33e00-8b70-11eb-9efd-5561c9484790.png">

after a tiny resize it has the correct values and the camera works:
<img width="926" alt="image" src="https://user-images.githubusercontent.com/776816/112071772-cb662880-8b70-11eb-90d6-48253072a3b1.png">

note that I am testing this on MacOS

**Comment by extrawurst** [comment]
so I added some more debugging to the `Context::new` and `resize_event` for `Stage`
```
new context: 1600,1200
resize_event: 807,608
resize_event: 807,609
resize_event: 811,614
resize_event: 812,615
```

so it looks like the first window size everything gets initialised with is off. note that 1600x1200 is not even my screen res, I am wondering where it gets this value from.

**Comment by not-fl3** [comment]
Connected(probably) issue: https://github.com/not-fl3/macroquad/issues/154

Unfortunately it will take some time to fix - while that kind of issue usually have super simple solution its hard to debug those without a mac :(

**Comment by extrawurst** [comment]
@not-fl3 if you have a hint where to start I can support you

**Comment by ollej** [comment]
I’m having the same issue on Mac. Wasm and windows seem to work fine.

**Comment by not-fl3** [comment]
> @not-fl3 if you have a hint where to start I can support you

I would start by tracing all the size events miniquad's objc code. I am pretty sure somewhere width/height are not being multiplied on highdpi scale factor or something like this :)

**Comment by extrawurst** [comment]
@not-fl3 I had a first look, the problem lies way deeper. stepping through the debugger it appears that on app start a hdpi factor is multiplied to calculate the frame buffer size (see `applicationDidFinishLaunching`):
https://github.com/not-fl3/miniquad/blob/eec0d1dce08c49c5420ba81b98b2962d16f3f304/native/sapp-darwin/external/sokol/sokol_app.h#L1305

the same seems to be not happening on resize (see `_sapp_macos_update_dimensions`):
https://github.com/not-fl3/miniquad/blob/eec0d1dce08c49c5420ba81b98b2962d16f3f304/native/sapp-darwin/external/sokol/sokol_app.h#L1278

**Comment by extrawurst** [comment]
seems like this was fixed in the meantime in the sokol lib you use here.
see https://github.com/floooh/sokol/blob/master/sokol_app.h#L2494

**Comment by extrawurst** [comment]
related to https://github.com/not-fl3/miniquad/pull/174

**Comment by extrawurst** [comment]
@not-fl3 PR done: https://github.com/not-fl3/miniquad/pull/192

**Comment by not-fl3** [comment]
Thank you @extrawurst!

Should be fixed now, feel free to reopen if it is not
