### ISSUE TITLE
Using wasm with macroquad

### ISSUE THREAD

**Issue by ZeroTixDev** [not-fl3/macroquad#178]
I came by this library because I heard its very simple and can compile into wasm. I copied one of the examples and it worked but when i tried to put it on web with the instructions, i kept seeing the same error. I even cloned one of the examples and did the exact steps and i got the same error. The error was : 
![image](https://user-images.githubusercontent.com/67355595/112182690-e322c880-8bd3-11eb-8cd5-0a479ab5f7df.png)
Please help!!

**Comment by not-fl3** [comment]
What macroquad version are you on? 
For the latest one this https://not-fl3.github.io/miniquad-samples/gl-0.1.23.js hosted gl.js file should do the job

**Comment by ZeroTixDev** [comment]
I updated to the code you just gave me and it shows the same error @not-fl3

**Comment by not-fl3** [comment]
What macroquad version are you using?

**Comment by ZeroTixDev** [comment]
I think I was the latest version but when im trying to build, im running into an error asking if i have gcc.exe installed but even after I installed cygwin, I am still getting the same error :/

**Comment by ZeroTixDev** [comment]
0.2.9

**Comment by ZeroTixDev** [comment]
@not-fl3

**Comment by not-fl3** [comment]
If you do not have a strong reason to use 0.2 - I would really recommend to switch to "0.3.0-alpha". A lot of things got fixed since 0.2. 
I would check what gl.js version was used back to 0.2, was pretty long time ago, will need some time to figure this out

**Comment by ZeroTixDev** [comment]
ty ty its working now :) a slight issue is if i want to use assets, i need to duplicate them in www and src

**Comment by wait-what** [comment]
It is bad practice, but you could compile your assets into the binary using `include_bytes!("./file.png")`

**Comment by Ryan1729** [comment]
> It is bad practice, but you could compile your assets into the binary using `include_bytes!("./file.png")`

Why would that be a bad practice?

**Comment by Zageron** [comment]
@not-fl3 I am also encountering this now.

```toml
...

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
macroquad = "0.3.0-alpha"
serde = "1"
serde_json = "1"
```

```rust
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>My Rust + Webpack project!</title>
  </head>
  <body>
    <canvas id="glcanvas" tabindex='1'></canvas>
    <script src="gl.js"></script>
    <!-- <script src="https://github.com/not-fl3/miniquad/blob/master/native/sapp-wasm/js/gl.js"></script>
    <script src="./index.js"></script> -->
    <script>load("rrr_game.wasm");</script>
  </body>
</html>
```

```
WASM failed to load, probably incompatible gl.js version gl.js:1:28123
    load http://localhost:8000/gl.js:1
    (Async: promise callback)
    load http://localhost:8000/gl.js:1
    <anonymous> http://localhost:8000/:12
TypeError: a.exports.main is not a function
    load http://localhost:8000/gl.js:1
    promise callback*load http://localhost:8000/gl.js:1
    <anonymous> http://localhost:8000/:12
gl.js:1:28197
    load http://localhost:8000/gl.js:1
    (Async: promise callback)
    load http://localhost:8000/gl.js:1
    <anonymous> http://localhost:8000/:12
```

**Comment by not-fl3** [comment]
```
[lib]
crate-type = ["cdylib"]
```

I am not sure about this part in your Cargo.toml, maybe that is the reason why rust did not exported `main`?

**Comment by Zageron** [comment]
> 
> 
> ```
> [lib]
> crate-type = ["cdylib"]
> ```
> 
> I am not sure about this part in your Cargo.toml, maybe that is the reason why rust did not exported `main`?

That was it, my mistake. Had my toml set up for webpack and didn't change it back.

**Comment by not-fl3** [comment]
Looks like both problems in this issue got solved, closing this :)

**Comment by gravit22** [comment]
I enconter similar issue. 
![image](https://user-images.githubusercontent.com/33228017/115272034-9f759d00-a146-11eb-98f9-a7338a9939cb.png)
![image](https://user-images.githubusercontent.com/33228017/115272090-aef4e600-a146-11eb-91c4-48a48e15b61e.png)
Cargo.toml:
`[package]
name = "simple_game"
version = "0.1.0"
authors = ["gravit22 <mikhail.gavrilec@gmail.com>"]
edition = "2018"


[dependencies]
macroquad = "0.3"`

main.rs just copied and pasted asteroids.rs. It works fine for OS, but doesn't work otherwise.

**Comment by not-fl3** [comment]
Oh, you right, thanks for report, should be fixed now

**Comment by abdokhe** [comment]
Hi I encountered an issue it generates the .html and gl.js

when I host the static files and browse the index.html url

this happens in the console

> [Log] Live reload enabled. (index.html, line 57)
> [Warning] No __wbindgen_describe function in gl.js (gl.js, line 1395)
> [Warning] No __wbindgen_throw function in gl.js (gl.js, line 1395)
> [Warning] No __wbindgen_externref_table_grow function in gl.js (gl.js, line 1395)
> [Warning] No __wbindgen_externref_table_set_null function in gl.js (gl.js, line 1395)
> [Warning] No audio_init function in gl.js (gl.js, line 1395)
> [Error] WASM failed to load, probably incompatible gl.js version
> 	(fn anonyme) (gl.js:1429)
> [Error] TypeError: import __wbindgen_placeholder__:__wbindgen_describe must be an object
> 	(fn anonyme) (gl.js:1430)

the toml file is this

```toml
[package]
name = "macro-proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "macro-proj"

[dependencies]
image = "0.24.7"
macroquad = "0.3.25"
```

1. when I checked the macro quad Cargo.toml in the repo it had the image crate that load just png image and in my project I reinstalled image crate to make the other formats available how to edit the macro quad Cargo.toml image crate formats?
2. and how to load images without blocking the main thread?
3. and how to make a progress bar?

**Comment by not-fl3** [comment]
apparently image is using wasm-bindgen now? You can either setup wasm-bindgen build process (https://github.com/not-fl3/macroquad/issues/212#issuecomment-835276147, never did it myself, looks too complicated for me) or use some other crate/image formats to avoid dealing with wasm-bindgen in your dependencies

**Comment by abdokhe** [comment]
ty and how about loading images without blocking the main thread?

**Comment by not-fl3** [comment]
> ty and how about loading images without blocking the main thread?

not really possible :(

**Comment by Zageron** [comment]
> ty and how about loading images without blocking the main thread?

You can create a worker thread to do your image loading if you are using wasm. It's moderately complex the first time but is very possible.

**Comment by abdokhe** [comment]
@Zageron
> You can create a worker thread to do your image loading if you are using wasm. It's moderately complex the first time but is very possible.

yeah I tried using standard library threads but the functions `load_texture` and `load_image` returns a Future which needs the closure inside thread::spawn to be async and that's not possible I imported futures crate to use the block_on but it doesn't work, then I tried adding Arc<Mutex<Vec<Image>>> to store images it didn't work also, and also using mpsc to send from the spawned thread to the main thread but it gives a seg fault. maybe it's not possible in macroquad.

and if someone need some help for something like this I used a hacky solution:
so for example you have 10 images in the drawing loop you load images one by one.

**Comment by Zageron** [comment]
https://github.com/Zageron/rrr/blob/e622284dfcf63d54be95075869a45357de54c3c3/crates/rrr_fetch/src/fetch/imp/platform/wasm.rs

This is old, and I didn't end up continuing with this method, but check out gloo worker to learn how to run things in async context in another thread on wasm. As long as you can copy the data across it should work just fine!
