### ISSUE TITLE
Circles in macroquad...

### ISSUE THREAD

**Issue by ZeroTixDev** [not-fl3/macroquad#179]
...Why 
![image](https://user-images.githubusercontent.com/67355595/112245582-8fda6580-8c27-11eb-9986-51512707874c.png)

**Comment by ZeroTixDev** [comment]
@not-fl3

**Comment by extrawurst** [comment]
@ZeroTixDev what is your question? 

> why?

does not give a lot of context to what exactly you are wondering about.

if you want control over how many line segments shall be used to approximate a circle use `draw_poly`

**Comment by extrawurst** [comment]
@ZeroTixDev any further questions or can this be closed?
