### ISSUE TITLE
Window size

### ISSUE THREAD

**Issue by yuuretsu** [not-fl3/macroquad#22]
Сan i set the window size? and can i forbid changing it?
---
Можно ли задать размеры окна и запретить пользователю ресайзить его?

**Comment by optozorax** [comment]
Возникает вопрос: а как эта функция должна работать на стороне wasm? Там же нельзя размер браузера задать. А если требовать такую фичу, то под неё же будет логика приложения завязываться, и соответственно эта логика будет некорректно работать в браузере. Так что один из вариантов: вообще не предоставлять такую функцию и рассказать пользователям что они должны делать своё приложение так, чтобы оно не зависело от размера окна, если они хотят wasm.

**Comment by not-fl3** [comment]
Lets try to keep all public issues/prs in the same language :)
