### ISSUE TITLE
wasm browser error

### ISSUE THREAD

**Issue by gubbu** [not-fl3/macroquad#221]
My  [macroquad project](https://github.com/gubbu/rust_rock_paper_scissors_automata_macroquad) runs perfectly fine on the desktop client.

- I build it for the wasm target with:  `cargo build --target wasm32-unknown-unknown --release`
 - I copy the compiled .wam file from the `target/wasm32-unknown-unknown/release` folder to the html template.
 - I change one line in the html template to `<script>load("rock_paper_scisors_cellular_automata.wasm");</script> <!-- Your compiled wasm file -->` to load it.
 - When i view the website in my browser serving with` basic-http-server .` , I see a black screen/canvas.
In the inspector it shows the following errors:
```
No init_opengl function in gl.js mq_js_bundle.js:1:27586
WASM failed to load, probably incompatible gl.js version mq_js_bundle.js:1:28218
TypeError: wasm_exports.crate_version is not a function
    load https://not-fl3.github.io/miniquad-samples/mq_js_bundle.js:1
mq_js_bundle.js:1:28292
    load https://not-fl3.github.io/miniquad-samples/mq_js_bundle.js:1
```

Is this a bug? Does it have something to do with the used macroquad version I used? The thing is: It used to work a few months ago in the web browser too. The only thing that changed is https://not-fl3.github.io/miniquad-samples/mq_js_bundle.js

index.html file used:
```
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>TITLE</title>
    <style>
        html,
        body,
        canvas {
            margin: 0px;
            padding: 0px;
            width: 100%;
            height: 100%;
            overflow: hidden;
            position: absolute;
            background: black;
            z-index: 0;
        }
    </style>
</head>

<body>
    <canvas id="glcanvas" tabindex='1'></canvas>
    <!-- Minified and statically hosted version of https://github.com/not-fl3/macroquad/blob/master/js/mq_js_bundle.js -->
    <script src="https://not-fl3.github.io/miniquad-samples/mq_js_bundle.js"></script>
    <script>load("rock_paper_scisors_cellular_automata.wasm");</script> <!-- Your compiled wasm file -->
</body>

</html>
```

**Comment by not-fl3** [comment]
Hi! `0.2.9` is really old, you need a JS file from this version. 
Maybe https://not-fl3.github.io/miniquad-samples/gl-0.2.56.js
Let me know if this doesn't work, I'll try to look the exact version from `0.2.9`

(but `0.2` is really really old, too many things got fixed in 0.3, it may be worth it to update!)

**Comment by not-fl3** [comment]
One of the worst parts of 0.2 - it did not have nice errors on JS versions mismatch, which makes it hard to find appropriate JS :)

**Comment by gubbu** [comment]
using the link  https://not-fl3.github.io/miniquad-samples/gl-0.2.56.js gives the following errors:
`Loading failed for the <script> with source “https://not-fl3.github.io/miniquad-samples/gl-0.2.56.js%22”. 127.0.0.1:4000:25:1`
```
Uncaught ReferenceError: load is not defined
    <anonymous> http://127.0.0.1:4000/:26
127.0.0.1:4000:26:1
    <anonymous> http://127.0.0.1:4000/:26
```

**Comment by gubbu** [comment]
Thanks for the fast help. Now i have gone through the hassle to update to `0.3`, the api changed quite a bit. it works like a charm ;)
but will the https://not-fl3.github.io/miniquad-samples/mq_js_bundle.js be updated again and introduce breaking changes for 0.4/newer versions? should one just download the current version of the js script to keep the website stable?

**Comment by not-fl3** [comment]
The safest way is to download and host .js alongside your .wasm

Also you can use specific version from miniquad-samples, like https://not-fl3.github.io/miniquad-samples/mq_js_bundle_0.3.1.js
