### ISSUE TITLE
How to change networking to server-authoritative

### ISSUE THREAD

**Issue by infcodey** [not-fl3/macroquad#233]
Hello,

I would like to change the networking from master-client-authoritative to server-authoritative. 

I would appreciate any advice on how to go about this, thank you.

**Comment by not-fl3** [comment]
Hello! 
Hmm, are you sure that the question is for macroquad? We do not have any networking at all!

**Comment by infcodey** [comment]
I see... sorry about that!

**Comment by not-fl3** [comment]
> I just realized that I posted this issue on the wrong repo, sorry!

No worries :)
