### ISSUE TITLE
toggle fullscreen

### ISSUE THREAD

**Issue by nacl42** [not-fl3/macroquad#236]
First things first: macroquad is a really great library. Thanks!

Is it possible to switch fullscreen mode during program execution? I have only found the option to specify fullscreen in the window_conf, which is read on window initialisation, but I would like to change it dynamically, e.g. by calling some function set_fullscreen(true|false).

**Comment by not-fl3** [comment]
Let's move that discussion to https://github.com/not-fl3/macroquad/issues/629
