### ISSUE TITLE
Multi-Pass Rendering

### ISSUE THREAD

**Issue by hazelLanes** [not-fl3/macroquad#24]
Miniquad itself has RenderPasses for rendering to a texture for post-processing or other. I have thus far not been able to figure out any way to accomplish something like this with macroquad. Is there a way I have just overlooked, or is this simply not implemented yet?

**Comment by not-fl3** [comment]
post effects of any kind are not yet implemented in macroquad :(

**Comment by not-fl3** [comment]
Now macroquad have some post-processing! 

Example: https://github.com/not-fl3/macroquad/blob/master/examples/post_processing.rs
Web build: https://not-fl3.github.io/miniquad-samples/post_processing.html
