### ISSUE TITLE
macroquad_macro: No license file or readme file include

### ISSUE THREAD

**Issue by remilauzier** [not-fl3/macroquad#246]
Hi. Fedora would like to have a license file and a readme if possible.
https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/
https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_documentation

**Comment by not-fl3** [comment]
honestly, I do not really like the idea of all this stuff in such an internal crate, but if you really need those - I would accept a PR
