### ISSUE TITLE
Runtime panic with newer versions of Tiled maps (1.6+)

### ISSUE THREAD

**Issue by jkelanne** [not-fl3/macroquad#252]
The version number in the Tiled map file has changed since version 1.6. Previously the version number was noted as a number, but since version 1.6 the type was changed to string. 

Run will panic when loading map files made with newer versions of Tiled.
``thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DeJsonErr { msg: "Unexpected token Str expected floating point ", line: xx, col: xx }'``

Reference to tiled documentation:
https://doc.mapeditor.org/en/stable/reference/json-map-format/#map

**Comment by not-fl3** [comment]
Fixed with https://github.com/not-fl3/macroquad/commit/1de5a37f68786e6e737a551f4dcad5668b017a15
