### ISSUE TITLE
shadertoy example

### ISSUE THREAD

**Issue by alekspickle** [not-fl3/macroquad#26]
Could not run shadertoy example. 
**rustc** spits out this
```
thread 'main' panicked at 'Not such texture: rust.png', src/texture.rs:20:50
``` 
But the error message is clear and reason is obvious, so I sorted it out. 
But the question remains. Would not it be better to update paths to run from the root of the crate, without going under `/examples`?
Totally for you to decide.
The demo is AWESOME. Especially when I am learning shaders now and able to understand how it works.

**Comment by zotho** [comment]
Resolved by PR https://github.com/not-fl3/macroquad/pull/25.
By this line: https://github.com/not-fl3/macroquad/pull/25/files#diff-f13d7ec453dff44384f2edeb9783472bR9

**Comment by extrawurst** [comment]
I don't get it. when this PR was merged why does this still fail?

**Comment by alekspickle** [comment]
@extrawurst what are you trying to run?

**Comment by extrawurst** [comment]
just realize its a different panic:

```
RUST_BACKTRACE=1 cargo r --example shadertoy                                            101 ↵  10150  11:47:28
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/examples/shadertoy`
thread 'main' panicked at 'not implemented', src/camera.rs:161:9
stack backtrace:
   0: std::panicking::begin_panic
             at /Users/stephan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:497
   1: <macroquad::camera::Camera3D as macroquad::camera::Camera>::render_pass
             at ./src/camera.rs:161
   2: macroquad::set_camera
             at ./src/lib.rs:415
   3: shadertoy::amain::{{closure}}
             at ./examples/shadertoy.rs:43
```

**Comment by extrawurst** [comment]
@AKholetsky should I create a new issue?

**Comment by not-fl3** [comment]
This should be fixed on `0.3` branch.

**Comment by Aplosion** [comment]
This issue can be closed, right?

Code works on my system when rust.png is present.

**Comment by not-fl3** [comment]
Looks so!
