### ISSUE TITLE
WASM Error when using Macroquad 0.3.7

### ISSUE THREAD

**Issue by Pebaz** [not-fl3/macroquad#268]
I'm trying to use the new `play_sound` and other `macroquad::audio` functions and I'm getting the same error as #221 except I'm using [mq_js_bundle_0.3.1.js](https://not-fl3.github.io/miniquad-samples/mq_js_bundle_0.3.1.js) and Macroquad 0.3.7:

![image](https://user-images.githubusercontent.com/28033767/127698911-e5310637-d3db-47fc-830f-2d6bddefbbdf.png)

Is there a cutting edge development version of the GL.js or the bundle.js (for using `quad-snd`/`macroquad::audio::play_sound`, etc.) that I could reference? I'm fine with updating it whenever I do a WASM build.

```html
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>TITLE</title>
    <style>
        html,
        body,
        canvas {
            margin: 0px;
            padding: 0px;
            width: 100%;
            height: 100%;
            overflow: hidden;
            position: absolute;
            background: black;
            z-index: 0;
        }
    </style>
</head>

<body>
    <canvas id="glcanvas" tabindex='1'></canvas>
    <!-- Minified and statically hosted version of https://github.com/not-fl3/macroquad/blob/master/js/mq_js_bundle.js -->
    <!-- <script src="https://not-fl3.github.io/miniquad-samples/mq_js_bundle.js"></script> -->
    <script src="https://not-fl3.github.io/miniquad-samples/mq_js_bundle_0.3.1.js"></script>
    <script>load("/target/wasm32-unknown-unknown/release/ll000.wasm");</script> <!-- Your compiled wasm file -->
</body>

</html>
```

**Comment by not-fl3** [comment]
pointer lock/audio errors are intresting, but I do not really see any Time/Instant calls in macroquad/quad-snd code. Maybe there is some Time/Instant call in your game's code?

**Comment by Pebaz** [comment]
Ah, yes I removed the calls to std::time::SystemTime::now() and it worked! :D

However, there are still the pointer errors and for some reason the audio didn't start until it was triggered again in game (I have looping audio starting out but it didn't start until I pressed a button which also plays a sound. It seemed like it just continued from where it was).

I'm good to keep it like this for now but do you have any thoughts on what the pointer issues could be? I'm not using any pointers in my own code but it's possible a library is.

![image](https://user-images.githubusercontent.com/28033767/127708650-55a1debc-610c-45a4-9662-ba5f0028770d.png)

**Comment by Pebaz** [comment]
Interesting find, the music starts just fine if I click into the viewport fast enough upon page load. Not sure why but that consistently works.

**Comment by not-fl3** [comment]
> Ah, yes I removed the calls to std::time::SystemTime::now() and it worked! :D
> 
> However, there are still the pointer errors and for some reason the audio didn't start until it was triggered again in game (I have looping audio starting out but it didn't start until I pressed a button which also plays a sound. It seemed like it just continued from where it was).
> 
> I'm good to keep it like this for now but do you have any thoughts on what the pointer issues could be? I'm not using any pointers in my own code but it's possible a library is.
> 
> ![image](https://user-images.githubusercontent.com/28033767/127708650-55a1debc-610c-45a4-9662-ba5f0028770d.png)

it is a browser restriction - you need to click something before the browser will allow music

usually it is auto-fixed with itch.io's Play game button that loads the game

**Comment by Pebaz** [comment]
Oh wow I didn't know that, thank you for looking into this!

If you're interested, here's a playable version of the miniature game: https://www.reddit.com/r/rust_gamedev/comments/ouu7xk/liminal_lab_000_my_first_ever_3d_game/?utm_medium=android_app&utm_source=share
