### ISSUE TITLE
macroquad_tiled::load_map() Unexpected token

### ISSUE THREAD

**Issue by taewyth** [not-fl3/macroquad#272]
Trying to go through the multiplayer game tutorial, I'm stuck on loading the level as `load_map()` returns an error:

`DeJsonErr {msg: "Unexpected token F64(1.4) expected string", line: x, col: y }`

my cargo.toml dependencies are:
`macroquad = "0.3"`
`macroquad-tiled = "0.1"`

running on Win10

Edit: tried using `macroquad-tiled = "0.1.1"`, the issue is still there

**Comment by not-fl3** [comment]
Assuming you are trying to load map.json from heroiclabs/fishgame-macroquad repo: just updated that map.json, the error should be fixed https://github.com/heroiclabs/fishgame-macroquad/commit/f73938a93d51c20abd82004a560a18622aff9dd3

**Comment by taewyth** [comment]
That was indeed the issue

**Comment by not-fl3** [comment]
Perfect!
