### ISSUE TITLE
Old versions of Tiled uses version as a float, not a String, so maps from these versions will not parse

### ISSUE THREAD

**Issue by olefasting** [not-fl3/macroquad#278]
Don't know if this is the right place for this, as the Tiled part of macroquad is a separate crate. Could not find a separate repo for this crate, however, so I'll make an issue here:

Parsing maps from newer versions of Tiled returns an error as version in these maps are now a Float, not a String.

EDIT:
Seems like I had an old version, due to using apt on Ubuntu. It might be worth accommodating for both cases but not a priority issue, I'm sure....

**Comment by not-fl3** [comment]
https://github.com/not-fl3/macroquad/commit/1de5a37f68786e6e737a551f4dcad5668b017a15 

ohhh, so they went back to float? bad news! 

it looks like it is easier to just remove `version` field completely, it is crazy that tiled change this all the time

**Comment by olefasting** [comment]
No, I'm sorry. This is due to Ubuntu installing an old version (1.4).
I'm gonna rename the issue to accommodate for this fact

**Comment by not-fl3** [comment]
This is correct, the minimum supported Tiled version is 1.8 (I guess?).
