### ISSUE TITLE
incompatible gl.js version

### ISSUE THREAD

**Issue by paul-asvb** [not-fl3/macroquad#291]
sorry for a similar error again. i already saw the other issues.
https://github.com/not-fl3/macroquad/issues/268
https://github.com/not-fl3/macroquad/issues/178

I have a similar problem.
[i followed your readme](https://github.com/not-fl3/macroquad#wasm)

sample code in this repo.
https://github.com/paul-asvb/rust-testgame

tried loading different versions of the mq_js file (master, 0.3.0, 0.3.1) all log the same error:
<img width="641" alt="Screenshot 2021-09-09 at 23 48 27" src="https://user-images.githubusercontent.com/4126256/132767646-dc4c7a39-5485-46da-b6dd-31e29ce98b93.png">

**Comment by not-fl3** [comment]
Incorrect response MIME tells that your web server do not support .wasm

Recommended one is `basic-http-server`, like here: https://github.com/not-fl3/macroquad#wasm

**Comment by paul-asvb** [comment]
Thanks for the fast reply. Works.
