### ISSUE TITLE
set_camera function not working correctly

### ISSUE THREAD

**Issue by GerodruS** [not-fl3/macroquad#293]
Looks like https://github.com/not-fl3/macroquad/tree/e5fce26e6cd436f2b57e08931e1d32a37c361bff commit broke some camera logic.

I have find out the issue with my project, but at least arkanoid.rs from examples folder works fine on the commit before and starting to show something strange with this one.

arkanoid before e5fce26e6cd436f2b57e08931e1d32a37c361bff commit
<img width="805" alt="Screenshot 2021-09-18 at 11 18 25" src="https://user-images.githubusercontent.com/4328501/133882041-16ddc00b-3b19-49a2-915b-e19a9ed7cc80.png">

arkanoid with e5fce26e6cd436f2b57e08931e1d32a37c361bff commit 
<img width="806" alt="Screenshot 2021-09-18 at 11 17 41" src="https://user-images.githubusercontent.com/4328501/133882055-22082a51-7b23-4302-82b4-e2a3b39cf81c.png">

**Comment by GerodruS** [comment]
After some tests, I found out, that camera value is overridden by default value of Scene (see the last line of snippet below).
```
impl Scene {
    pub fn new() -> Self {
        Scene {
            dense: vec![],
            dense_ongoing: vec![],
            nodes: Vec::new(),
            arena: bumpalo::Bump::new(),
            free_nodes: Vec::new(),
            camera: [Some(Camera2D::default()), None, None, None],
```

**Comment by GerodruS** [comment]
Attempt to replace call of `macroquad::camera::set_camera` function by `macroquad::experimental::scene::set_camera` at `arkanoid.rs` still was unsuccessful, because of `crate::prelude::set_default_camera();` line at Scene.update function:
```
        for camera in self.camera.iter() {
            if let Some(camera) = camera {
                self.camera_pos = camera.target;
                crate::prelude::set_camera(&*camera);

                for node in &mut self.iter() {
                    let cell = self.nodes[node.handle.0.id].as_mut().unwrap();
                    let node: RefMut<()> = node.to_typed::<()>();
                    unsafe { (*cell.draw)(node) };
                }

                crate::prelude::set_default_camera(); // this line
            }
        }
```

**Comment by not-fl3** [comment]
Oh, thanks for report, scenes should not intereference with a normal camera logic, will fix!

**Comment by not-fl3** [comment]
As a workaround you can do: 

```diff
-    // build camera with following coordinate system:
-    // (0., 0)     .... (SCR_W, 0.)
-    // (0., SCR_H) .... (SCR_W, SCR_H)
-    set_camera(&Camera2D {
-        zoom: vec2(1. / SCR_W * 2., -1. / SCR_H * 2.),
-        target: vec2(SCR_W / 2., SCR_H / 2.),
-        ..Default::default()
-    });
-
     loop {
         clear_background(SKYBLUE);
 
+        // build camera with following coordinate system:
+        // (0., 0)     .... (SCR_W, 0.)
+        // (0., SCR_H) .... (SCR_W, SCR_H)
+        set_camera(&Camera2D {
+            zoom: vec2(1. / SCR_W * 2., -1. / SCR_H * 2.),
+            target: vec2(SCR_W / 2., SCR_H / 2.),
+            ..Default::default()
+        });
+
```

**Comment by not-fl3** [comment]
Should be fixed with https://github.com/not-fl3/macroquad/commit/46ba1624963033bc0e2eabb637ae1d2f6af2fd90

**Comment by GerodruS** [comment]
Current version -- 0.3.10 has no more this issue.
Thank you!
