### ISSUE TITLE
KeyCode::CapsLock Doesn't Work.

### ISSUE THREAD

**Issue by eboatwright** [not-fl3/macroquad#295]
My code:
if is_key_pressed(KeyCode::CapsLock) {
    println!("caps lock");
}
I'm on MacOS Catalina 10.15.7,
rustup 1.24.3,
rustc 1.55.0,
macroquad 0.3

**Comment by not-fl3** [comment]
It looks like MacOs just do not send keypress events for capslock: https://stackoverflow.com/questions/12536356/how-to-detect-key-up-or-key-release-for-the-capslock-key-in-os-x/22286874#22286874

Not sure how to fix it tho, probably the only thing we can do - add a comment for CapsLock keycode that it is not available on Mac?

**Comment by eboatwright** [comment]
Yeah. :(
