### ISSUE TITLE
Blurry text using `draw_text`

### ISSUE THREAD

**Issue by Catman155** [not-fl3/macroquad#30]
When using the `draw_text` method, the text drawn is blurry at higher font sizes. Doe this have to do with the fact that a picture is used as a font? Is there a way to get a better looking text at higher font sizes?

**Comment by luciusmagn** [comment]
Hi, I'm experiencing this as well, and I think it concerns pretty much all sizes

**Comment by gubbu** [comment]
Its the filter Mode:
pub enum FilterMode {
    Linear = GL_LINEAR as isize,
    Nearest = GL_NEAREST as isize,
}
When the texture mode is set to "Linear" (the default) you get blurred results of the pixel fonts... I guess the problem is: context.font_texture FilterMode is set to "Linear" instead of Nearest?

**Comment by extrawurst** [comment]
> Its the filter Mode:
> pub enum FilterMode {
> Linear = GL_LINEAR as isize,
> Nearest = GL_NEAREST as isize,
> }
> When the texture mode is set to "Linear" (the default) you get blurred results of the pixel fonts... I guess the problem is: context.font_texture FilterMode is set to "Linear" instead of Nearest?

Nearest will only make it more pixelated and jaggy. in the end the font texture resolution would need to be bigger to prevent this

**Comment by SrMordred** [comment]
Any updates regarding this ? 
If not, any points on how to solve this ?
I can help with PR (although i'm not experienced )
