### ISSUE TITLE
Any chance for this to work on Wayland?

### ISSUE THREAD

**Issue by yujiri8** [not-fl3/macroquad#306]
`XOpenDisplay() failed!` followed by a segfault is the result I get when I try to run it without Xwayland running.

**Comment by not-fl3** [comment]
> is not going to be merged anytime soon

Guess what, that "soon" actually happened and the branch got merged :) 
Still very far from full wayland support, but quads can draw things natively on wayland now

**Comment by treeshateorcs** [comment]
how do i force it to use wayland? i still get `XOpenDisplay() failed!`

**Comment by treeshateorcs** [comment]
i think this line

https://github.com/not-fl3/miniquad/blob/fdd551ea6a11985e9b404c0c087cd536208db496/src/conf.rs#L134

should be

```
linux_backend: LinuxBackend::WaylandWithX11Fallback,
```
