### ISSUE TITLE
Access radius of macroquad::math::Circle

### ISSUE THREAD

**Issue by Alch-Emi** [not-fl3/macroquad#317]
I'm working a little bit with the `Circle` struct from the math module, and I can't seem to find a way to access the radius of the circle after it has been constructed.  While `x` and `y` may be accessed using the `.point()` method, it seems like the radius, while stored, is never made accessible.

My workaround is just to store the radius alongside the circle when I'm working with the `Circle` struct, but this feels a little clumsy and unnecessary.

Is there a reason why access to the circles radius is restricted?  Are there plans to change the structs API surface later?  Would a PR be accepted to expose the radius?

Thank you for your help!

**Comment by not-fl3** [comment]
Sure, go ahead with a PR!
