### ISSUE TITLE
Android keyboard support

### ISSUE THREAD

**Issue by sonicrules1234** [not-fl3/macroquad#318]
On android, there is currently no way to input anything that takes keyboard input, not even with a bluetooth keyboard.  If that could be implemented, then people would be able to make android apps much easier.

**Comment by buxx** [comment]
Hello @not-fl3 ,

Would you have time to look at what kind of modifications this requires so that I or someone can try to make it possible ? :)

**Comment by not-fl3** [comment]
>  or someone can try to make it possible ? :)

Someone absolutely can! :D 
I would not do it myself until I will have a good case for this myself, I would like to have a nice good test case to make sure it absolutely do works, so will not promise that I will do it anytime soon

**Comment by buxx** [comment]
Okay. I personally have a case, my game require a login/password home page screen. I would be happy to implement it and add a test case in macroquad example folder. But, I don't know how to start :s

**Comment by sonicrules1234** [comment]
> Okay. I personally have a case, my game require a login/password home page screen. I would be happy to implement it and add a test case in macroquad example folder. But, I don't know how to start :s

If you look in ndk-sys there are functions for bringing up the soft keyboard, and some events to go with it.  You might have to add to miniquad before doing stuff with macroquad.

**Comment by buxx** [comment]
@sonicrules1234 I'm searching which ndk-sys function should be called. Is that [ANativeActivity_showSoftInput](https://docs.rs/ndk-sys/latest/ndk_sys/fn.ANativeActivity_showSoftInput.html) ?

**Comment by sonicrules1234** [comment]
> @sonicrules1234 I'm searching which ndk-sys function should be called. Is that [ANativeActivity_showSoftInput](https://docs.rs/ndk-sys/latest/ndk_sys/fn.ANativeActivity_showSoftInput.html) ?

That's right.

**Comment by macnelly** [comment]
Is there any progress on this? I would also like to be able to open the virtual keyboard when e.g. inside a editbox or input_text.

**Comment by macnelly** [comment]
There are examples for virtual keyboard at quad-android-playground repository:
https://github.com/not-fl3/quad-android-playground/blob/main/src/main.rs

**Comment by not-fl3** [comment]
thanks @macnelly 

yes, I believe this is fixed now
