### ISSUE TITLE
Keyboard input bug

### ISSUE THREAD

**Issue by eboatwright** [not-fl3/macroquad#322]
So. This one is really hard to explain. So, basically I am working on a 2 player game. Each player can move horizontally and jump. So basically I figured out that if one of the players is moving (let's just say player 1 is moving right) and then player 2 holds down left, right and up, then when I let go of player 1's right key, player 1 keeps moving right. I have no idea why this happens. I am using "is_key_down" for moving left and right and "is_key_pressed" for jump.

**Comment by not-fl3** [comment]
It might be a bug!

But just a random thought here - are you sure if the keyboard itself supports so much keypress? Typical keyboards have a hard limit on ~3 simultaneous keys and afterwards they start to act weird

**Comment by eboatwright** [comment]
Hm. I'll look into that

**Comment by eboatwright** [comment]
Oh ok this is actually a problem with my keyboard ¯\_(ツ)_/¯ Thank you! :D
