### ISSUE TITLE
How to make rotation and scaling not blurry?

### ISSUE THREAD

**Issue by eboatwright** [not-fl3/macroquad#325]
I'm working on my "game engine" using Macroquad and an HECS. And I'm working on my texture rendering, and I wanted to allow rotation and scaling. What I can't figure out is, how to make rotation and scaling not blurry? I'm using the function "draw_texture_ex" for rendering.

**Comment by MikeeyBikeey** [comment]
You can set the filter mode by calling [`Texture2D::set_filter`](https://docs.rs/macroquad/0.3.13/macroquad/texture/struct.Texture2D.html#method.set_filter) with a specified [`FilterMode`](https://docs.rs/macroquad/0.3.13/macroquad/texture/enum.FilterMode.html).
```rust
let mut texture = load_texture("texture/path.png").await.unwrap();
texture.set_filter(FilterMode::Nearest); // `FilterMode::Nearest` works great for pixel art.
```

**Comment by eboatwright** [comment]
I did that, and it's still blurry

**Comment by eboatwright** [comment]
Oh OOPS! I messed it up, this actually does work!
