### ISSUE TITLE
`import object field '__wbindgen_placeholder__' is not an Object` with stock index.html in WASM

### ISSUE THREAD

**Issue by TheTechRobo** [not-fl3/macroquad#326]
See title.

![image](https://user-images.githubusercontent.com/52163910/144718778-27fd47a2-de2d-4466-8d2d-99290dd5d108.png)

If it helps, I am using two dependencies: rand, and getrandom (the latter has the "js" feature)

**Comment by TheTechRobo** [comment]
wasm32-wasi gives me `TypeError: import object field 'wasi_snapshot_preview1' is not an Object`.

**Comment by not-fl3** [comment]
`__wbindgen_placeholder__` means that you are using wasm-bindgen in your dependencies. Such dependencies implicitly expect you to use the `wasm-bindgen` third party binary alongside rust compiler. The process of using wasm-bindgen is quite complicated I personally do not recommend it, but if you really need it: https://github.com/not-fl3/macroquad/issues/212#issuecomment-835276147

**Comment by TheTechRobo** [comment]
In that case, do you know fo any alternatives to the `rand` crate?

**Comment by not-fl3** [comment]
there are plenty, but I would recommend `macroquad::rand`

**Comment by TheTechRobo** [comment]
That gives me `PanicInfo { payload: Any { .. }, message: None, location: Location { file: "library/std/src/sys/wasm/../unsupported/time.rs", line: 39, col: 9 } }`

![image](https://user-images.githubusercontent.com/52163910/145116774-f30c0a78-1332-4999-8610-a8e759360ed6.png)

**Comment by not-fl3** [comment]
Yes, Instant is not available on wasm. You can use https://github.com/sebcrozet/instant (I never tried myself, but they used to have some cargo features that made it work with quads) or just `macroquad::time::get_time`

**Comment by TheTechRobo** [comment]
Thank you very much for your help! very new to the Rust ecosystem.
