### ISSUE TITLE
Toggle Mouse Visibility

### ISSUE THREAD

**Issue by chrisburnor** [not-fl3/macroquad#33]
I see that miniquad has the ability to toggle mouse visibility (https://docs.rs/miniquad/0.2.55/miniquad/graphics/struct.Context.html#method.show_mouse), but it doesn't look like that API is available in macroquad.

**Comment by Pebaz** [comment]
@chrisburnor I was able to do this using the below code:

```rust
let InternalGlContext { quad_context: ctx, ..} = unsafe { get_internal_gl() };

ctx.show_mouse(false);
ctx.set_cursor_grab(true);
```

**Comment by willmcpherson2** [comment]
I believe [this](https://docs.rs/macroquad/0.3.10/macroquad/input/fn.show_mouse.html) is available now? Can we close?

**Comment by not-fl3** [comment]
> I believe [this](https://docs.rs/macroquad/0.3.10/macroquad/input/fn.show_mouse.html) is available now? Can we close?

Yes, indeed :)
