### ISSUE TITLE
How to resize buttons for the immediate mode ui

### ISSUE THREAD

**Issue by Eisverygoodletter** [not-fl3/macroquad#330]
I've searched the docs and it seems like I can't resize buttons in made from
```rust
if root_ui().button(None, "some text here") {
    println!("button pressed");
}
```
Is there an alternative way to make buttons that I can set the size of? currently I only know how to set position and text.

(also I'm a beginner at Rust, am I missing something obvious?)

**Comment by not-fl3** [comment]
Yes, there is an alternative way: use a builder Button struct. 
This example may help: https://github.com/not-fl3/macroquad/blob/master/examples/ui.rs#L211

**Comment by Eisverygoodletter** [comment]
thanks!
