### ISSUE TITLE
button hitbox is offset from where the button actually is

### ISSUE THREAD

**Issue by Eisverygoodletter** [not-fl3/macroquad#331]
using this code 
```rust
use macroquad::prelude::*;
use macroquad::math::vec2;
use macroquad::ui::{root_ui, widgets};
#[macroquad::main("button testing")]
async fn main() {
    loop {
        clear_background(BLACK);
        if widgets::Button::new("push me").size(vec2(100.0, 100.0)).position(vec2(100.0, 100.0)).ui(&mut *root_ui()) {
            println!("button was pushed");
        }
        next_frame().await;
    }
}
```
This shows up
The yellow rectangle was added in by me to show approximately where the button could be clicked, and it doesn't line up with the actual button
![button testing](https://user-images.githubusercontent.com/76079042/145151732-cf1d8225-697d-4823-8061-554b80560ca4.png)
The hitbox (clickbox?) seems to have different offsets if I move the button to different parts of the screen. However, it always offsets towards the top left of the button.
any help?

**Comment by Eisverygoodletter** [comment]
update: after moving the button around a lot, it seems like the closer the "visual button" is closer to the bottom right corner, the larger the offset between the "visual button" and the "hitbox button". Also, they always seem to line up perfectly with the top left corner, so I think it might be a scaling issue.

**Comment by Eisverygoodletter** [comment]
Update 2: I believe the problem may be in the inconsistencies between `screen_height()` and `macroquad::input::mouse_position()` and their width counterparts. By using `screen_height()`, I get a value of `600` for the height. However, if I move my mouse down to the bottom of the screen, `macroquad::input::mouse_position().1` will give me `745` for the height. I think this may be causing scaling issues for the hitbox

**Comment by not-fl3** [comment]
Thanks for your research! It probably was caused by this PR: https://github.com/not-fl3/miniquad/pull/248 

Unfortunately, it is one of those rare bugs that do not reproduce under wine for me and I do not have a real windows machine right now.
So it may take a bit of time to fix :(

**Comment by Eisverygoodletter** [comment]
After messing around by resizing and moving the window around a bit, I found out that both `screen_height()` and `mouse_position().1` (when cursor positioned at bottom of screen) will both shrink proportionally to the window size. Basically they're shrinking on the same scale, and as the window gets smaller the distance between them get closer. 
Resizing the window doesn't change the button hitbox offset at all, so I'm still not sure what's happening. (`screen_height()` and `mouse_position()` differences might be another issue in itself)

**Comment by vpzomtrrfrt** [comment]
I believe I've also seen this issue on a linux system now

**Comment by vpzomtrrfrt** [comment]
Yes, under Ubuntu at least, enabling "Fractional Scaling" in the settings and selecting a non-100% scale causes this issue

**Comment by vpzomtrrfrt** [comment]
Bisecting shows faf5c7f as the relevant change

**Comment by not-fl3** [comment]
> Bisecting shows [faf5c7f](https://github.com/not-fl3/macroquad/commit/faf5c7f1c1cc91bfe6b6b3a29b802a5276b53a65) as the relevant change, so presumably the input values were missed when implementing hidpi

Thank you very much for your time on the bisecting, good catch! 

Feel free to reopen if the problem will still happen after the fix.
