### ISSUE TITLE
Add optional non-async next_frame(); function

### ISSUE THREAD

**Issue by mohamedSulaimanAlmarzooqi** [not-fl3/macroquad#332]
Hello
I'm wanting to use the call in some sync functions, However everyone knows that's not possible, I did read the reasons why it's async on the main page, And since I'm not going to build for mobile neither wasm so it's not a problem for me, Is there a way for a cargo_feature or something to be added to allow this?

**Comment by not-fl3** [comment]
I would say that technically it is possible(and probably quite simple), but will require too much maintenance work on two completely separate main loop implementations. (its not only next_frame, you will also need all the load_* functions.)

Also, this will create two separate API sets for different platforms, which is straight against macroquad's goals - being cross-platform. 

So it may deserve a PC-only fork if you really need it, but this will not land on macroquad anytime soon, so closing it for now.

**Comment by mohamedSulaimanAlmarzooqi** [comment]
Hi
I would forck and do it, However I'm unsure about how, Sorry, But can you please help me with a simple explanation? I just want the input to be updated without async stuff.
