### ISSUE TITLE
Android build crashes, cannot locate symbol "glStencilOpSeparate"

### ISSUE THREAD

**Issue by tirithen** [not-fl3/macroquad#338]
I build an apk package and install with:

```bash
$ docker run --rm -v $(pwd):/root/src -w /root/src notfl3/cargo-apk cargo quad-apk build --release
$ adb install target/android-artifacts/release/apk/app.apk
```

When I start the app on the Android phone (Fairphone 3 running Android 10) it crashes without displaying anything.

Running `adb logcat` I find errors where it fails to locale the symbol "glStencilOpSeparate":

```
12-12 12:26:17.002  7783  7783 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/app.example.com-xxxx==/lib/arm64/libapp.so": dlopen failed: cannot locate symbol "glStencilOpSeparate" referenced by "/data/app/app.example.com-xxxx==/lib/arm64/libapp.so"...
```

I have built this same project before for Android with the docker image builder without problems, but that was a few months ago and on another machine (Arch Linux both times).

I'm using `macroquad = { version = "0.3", features = ["log-impl"] }` in my Cargo.toml

---

Steps to reproduce in a new project:

```bash
$ mkdir androidtest
$ cd androidtest
$ cargo init
```
Add `macroquad = "0.3"` to dependency section of `Cargo.toml`

Open `src/main.rs` and replace the content with:

```rust
use macroquad::prelude::*;

#[macroquad::main("BasicShapes")]
async fn main() {
    loop {
        clear_background(RED);

        draw_line(40.0, 40.0, 100.0, 200.0, 15.0, BLUE);
        draw_rectangle(screen_width() / 2.0 - 60.0, 100.0, 120.0, 60.0, GREEN);
        draw_circle(screen_width() - 30.0, screen_height() - 30.0, 15.0, YELLOW);

        draw_text("IT WORKS!", 20.0, 20.0, 30.0, DARKGRAY);

        next_frame().await
    }
}
```

Build Android apk and install to Android device with:

```bash
$ docker run --rm -v $(pwd):/root/src -w /root/src notfl3/cargo-apk cargo quad-apk build --release
$ adb install target/android-artifacts/release/apk/androidtest.apk
```

Start the app on the phone (used Fairphone 3 with Android 10), then check logs with:

```bash
$ adb logcat | grep androidtest
```

For this new project it instead logs `cannot locate symbol "glAttachShader"`, but the pattern is otherwise similar:

```
12-12 13:21:45.807 14324 14324 E AndroidRuntime: Process: rust.androidtest, PID: 14324
12-12 13:21:45.807 14324 14324 E AndroidRuntime: java.lang.UnsatisfiedLinkError: Unable to load native library "/data/app/rust.androidtest-I71JsUQHONeEUuyI3-lZiA==/lib/arm64/libandroidtest.so": dlopen failed: cannot locate symbol "glAttachShader" referenced by "/data/app/rust.androidtest-I71JsUQHONeEUuyI3-lZiA==/lib/arm64/libandroidtest.so"...
12-12 13:21:45.809  1580 11173 W ActivityTaskManager:   Force finishing activity rust.androidtest/android.app.NativeActivity
12-12 13:21:45.893  1580  3662 I ActivityManager: Process rust.androidtest (pid 14324) has died: vis+99 TOP 
12-12 13:21:46.309  1580  1661 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{27523c1 u0 rust.androidtest/android.app.NativeActivity t-1 f}
12-12 13:21:48.049  1580  6690 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=rust.androidtest/android.app.NativeActivity bnds=[839,258][1039,540]} from uid 10023
12-12 13:21:48.084  1580  1674 I ActivityManager: Start proc 14354:rust.androidtest/u0a326 for activity {rust.androidtest/android.app.NativeActivity}
12-12 13:21:48.155 14354 14354 W NativeActivity: NativeActivity LoadNativeLibrary("/data/app/rust.androidtest-I71JsUQHONeEUuyI3-lZiA==/lib/arm64/libandroidtest.so") failed: dlopen failed: cannot locate symbol "glAttachShader" referenced by "/data/app/rust.androidtest-I71JsUQHONeEUuyI3-lZiA==/lib/arm64/libandroidtest.so"...
```

Are there some OpenGL libraries that needs to be linked during build to get access to the "glStencilOpSeparate" and "glAttachShader" symbols?

**Comment by not-fl3** [comment]
Hello! 
Thanks for the issue, yes, I can reproduce it! 

The issue is: android's build.rs https://github.com/not-fl3/miniquad/blob/master/native/sapp-android/build.rs somehow got lost during `cargo publish`, trying to figure why 

Just doing `cargo publish` from sapp_android folder again did not help, cargo just silently exclude `build.rs` from the publishing tarball...

**Comment by not-fl3** [comment]
```
> ls 
build.rs    Cargo.toml      LICENSE-MIT  src
Cargo.lock  LICENSE-APACHE  README.md    target

> ls build.rs
build.rs

> cargo publish --allow-dirty --no-verify --verbose
    Updating crates.io index
   Packaging sapp-android v0.1.13 (/home/fl3/tmp/sapp-android)
   Archiving Cargo.toml
   Archiving Cargo.toml.orig
   Archiving LICENSE-APACHE
   Archiving LICENSE-MIT
   Archiving README.md
   Archiving src/egl.rs
   Archiving src/gl3.rs
   Archiving src/lib.rs
   Archiving src/query_stab.rs
   Archiving src/rand.rs
   Archiving src/sokol_app.c
   Uploading sapp-android v0.1.13 (/home/fl3/tmp/sapp-android)
```

🤔

**Comment by not-fl3** [comment]
oh, I got it. We got a PR from some repo maintainer with the "include" tag in Cargo.toml, totally forgot about it :) Fix is on the way!

**Comment by not-fl3** [comment]
0.3.13 published with a fix!

**Comment by tirithen** [comment]
Thanks for the fast fix! I sponsored your project a small amount now as well, I'm not sure if I can continue each month yet, but hopefully more so in the future if the project I'm working on becomes more than a hobby at some point.

Thanks for two nice libraries, I was really inspired this spring when I was just getting started with Rust and found a pod cast where you presented miniquad and macroquad. Keep it up! :)

**Comment by not-fl3** [comment]
Thank you a lot, I really appreciate all donations, one time is perfectly fine, don't feel pressured to keep it! 

Feel free to reopen this if the fix did not really fixed the problem :)
