### ISSUE TITLE
Not building on Linux

### ISSUE THREAD

**Issue by eboatwright** [not-fl3/macroquad#339]
I'm currently trying out Linux distros and seeing which ones I like and everything, and I keep getting this error when building a project with macroquad.
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.12nw7lavcyvcyp38.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.1b8gofr01laaqhju.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.1gb6osipt6wtswyz.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.1hlyfag9jw5h0sv9.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.1j0s6d444xf2r866.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.1jzvdxh4w5od92xy.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.1lmlwwn6x3o6g9j4.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.1lpg6asvxt01het8.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.1mtmt1ddqwdzpjaz.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.1sc5yvwqq1e2le4l.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.1w43k8rfiorx4o0v.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.1y2d15zeoqzh4gta.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.227auftefv664zcb.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.22dndlb2dnqr5qh5.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.26w8pgeeqnaw8y0a.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.2dgz5ganrsp3u7t3.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.2ej5nwafnwy58l9j.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.2er90kpmcj392wia.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.2hnha71rtuv8oise.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.2pje411w8zhjjmyz.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.2q4lqlplwdvqc295.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.2ubtp6jwkyrfd60k.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.2uxrndkhmn7hmn34.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.2w8pq18uzl8a79gy.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.3h0w41i7m82pdsmq.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.3hjhg7xsdz6w5il5.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.3hx8fdrhetuhcm5x.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.3kl7dtoudstfeatc.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.3kw6dwrngsd0vits.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.3sd60y85ybxd3y3x.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.3wlax6jp03dxn60y.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.43yyt01ut4n03ceg.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.47uzh4n4kitvrpyd.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.48uzza42tb4ghoij.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4c3o80rdtxgnmdg2.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4d2qmeqs31so100y.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4d6y92uwzr5m3aib.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4eoiix3v726mog1o.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4h1fvo5aol86lfdx.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4jkjnl0aq4ymzmfi.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4jtmr35em9d81lhq.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4pnrsz82e8fapwfg.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4setg3l6ugqtfpx8.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4u03o54e7z9ktqof.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4v101kffr36fsptf.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4x9zleboame7jko2.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4yhfzi26p9uj5pjv.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.4ym691fzzwnrs8ri.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.51wwnngufdgycndn.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.52yxsrw6t8ms8szh.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.56hl98ywuooqnfmi.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.5880s3esmqh21nj0.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.59nu3l5ljsdxi0xa.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.5app22t2ra2jo7kl.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.5b8tupqrjfg1mkm8.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.7jq8m2c1gnpdgb8.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.evzfinhdz3bc7zs.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.ix5qfavvpd3j8u2.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.m2g71zp82wb8t57.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.rmuikb2l6n4wa6m.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.s4x5gmzo6fjohuc.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.sndnoi8uhx96djg.rcgu.o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd.27bhutbrh2q89nu7.rcgu.o" "-Wl,--as-needed" "-L" "/home/feren/Desktop/hello_rust/target/debug/deps" "-L" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/feren/Desktop/hello_rust/target/debug/deps/libhecs-03573bbe2bc4662e.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libhashbrown-1baf7b89d68f850a.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libahash-71ca5b90ec020ac6.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libgetrandom-0999061a33522995.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libonce_cell-ab6688537caa6b7e.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libmacroquad-0e1b5edd7be1903b.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libbumpalo-22b320eaf3d225f8.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libfontdue-0d55fa1e547eb68e.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libttf_parser-637019be111440f6.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libhashbrown-2937c4de4caa3818.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libahash-d79e429753639631.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libimage-1476ecd2f194afa6.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libcolor_quant-338ff96f7e350f21.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libnum_iter-813b26ba2e89f7f5.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libbytemuck-9e0f4c3cf8020abd.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libpng-ccbcb3f88a36a47a.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libminiz_oxide-76984392017d6dd1.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libcrc32fast-94967a3338965d92.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libcfg_if-ab143ea84ab1a05a.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libdeflate-88857c504c6920c6.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libadler32-d95e9260f201da4a.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libbitflags-61aba1fe2f663891.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libnum_rational-3f069137b1cd0144.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libnum_integer-172c7b4cd5351acc.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libnum_traits-fdcdcb928b8ee5a9.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libquad_rand-2f17e0044d6d36cb.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libglam-63e3b82abb54535f.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libquad_snd-22c88f0446b5db45.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libaudrey-23e0e8ea6f821e6e.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/liblewton-67021e82d8001c9c.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libogg-5f22fd90d451a674.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libsmallvec-6d48a99b00173e0c.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libmaybe_uninit-1a3a06c709685ce8.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libbyteorder-fd7ce5205f0a7dff.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libhound-eb97b9e6d132891e.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libdasp_frame-efa331e42ba191da.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libdasp_sample-29daf7768aa16100.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libquad_alsa_sys-ed06fadf2226e7c1.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libminiquad-5e4759919f04c27a.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/libsapp_linux-5809d36383aa51c9.rlib" "/home/feren/Desktop/hello_rust/target/debug/deps/liblibc-5af17482beb691ed.rlib" "-Wl,--start-group" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-7c582493123fc1dd.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-1392776590706175.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-2eb6edf4d031cd1e.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-33a7ad3b5f7fedf6.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-7d32adce541987d9.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-5cb369120f224726.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-6ab2efd1d2f431a9.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-567f611439253c7e.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-ebbc63efd6d2efc5.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-862830f0d224a2e1.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-cad0401ae7a80e32.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-fd54290077194763.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-4fc3313c8ccb1ec0.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-19bf8dffe82b09d4.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-afc95b1640c4beca.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-aff6658baa87e3d1.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-8be8a1689a4f7b48.rlib" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-5284934f66073844.rlib" "-Wl,--end-group" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-2a0b2a4f96acb821.rlib" "-Wl,-Bdynamic" "-lasound" "-lGL" "-lX11" "-lXi" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/feren/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/feren/Desktop/hello_rust/target/debug/deps/hello_rust-da64a48cb859f9cd" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lasound
          /usr/bin/ld: cannot find -lGL
          /usr/bin/ld: cannot find -lX11
          /usr/bin/ld: cannot find -lXi
          collect2: error: ld returned 1 exit status

**Comment by henriklundgren** [comment]
Maybe `alsa-lib-devel` is missing, and it seems some others as well.

**Comment by not-fl3** [comment]
```
 = note: /usr/bin/ld: cannot find -lasound
/usr/bin/ld: cannot find -lGL
/usr/bin/ld: cannot find -lX11
/usr/bin/ld: cannot find -lXi
```

you need to install those, depending on your distro:

```bash
# ubuntu system dependencies
apt install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev

# fedora system dependencies
dnf install libX11-devel libXi-devel mesa-libGL-devel alsa-lib-devel

# arch linux system dependencies
 pacman -S pkg-config libx11 libxi mesa-libgl alsa-lib
 ```

**Comment by eboatwright** [comment]
Oh! Thank you guys for your help! :D
