### ISSUE TITLE
Can't build to x86_64-pc-windows-gnu from Pop! OS

### ISSUE THREAD

**Issue by eboatwright** [not-fl3/macroquad#340]
I'm currently trying out Pop! OS and I'm trying to build a macroquad test project. x86_64-unknown-linux-gnu and wasm32-unknown-unknown work, but I'm trying to get a windows build working. When running the cargo build --target=x86_64-pc-windows-gnu command, I get this error: 
   Compiling lewton v0.9.4
   Compiling sapp-windows v0.2.19
   Compiling image v0.23.14
   Compiling miniquad v0.3.0-alpha.42
error: linker `x86_64-w64-mingw32-gcc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `lewton` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by not-fl3** [comment]
>  error: linker x86_64-w64-mingw32-gcc not found

you need to install it, I am not familiar with PopOs, probably its something like `mingw-w64` package

**Comment by eboatwright** [comment]
Yay it works! Thank you :D
