### ISSUE TITLE
"Unable to get OES_vertex_array_object extension"

### ISSUE THREAD

**Issue by eboatwright** [not-fl3/macroquad#344]
I am building from Pop!_OS (which is a Ubuntu based distro), and building to wasm32-unknown-unknown. It works fine when accessing it on my laptop, but when I try to access it from my mobile browser, I get the error listed above, followed by this error: "Can't initialize WEBGL_depth_texture extension"

**Comment by not-fl3** [comment]
Does your browser support webgl? Does https://get.webgl.org/ works fine?

**Comment by not-fl3** [comment]
Also worth checking browser version
https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_depth_texture

**Comment by eboatwright** [comment]
Yup. I'm using Brave Browser and when I load the get.webgl.org site on my device, it works.

**Comment by not-fl3** [comment]
I am not familiar with Brave Browser, but google said it might limit WebGl extensions due to fingerprinting protection settings. 

Lets keep this issue open, maybe someone familiar with Brave Browser will help
