### ISSUE TITLE
Windows Dispaly Scale breaks mouse position

### ISSUE THREAD

**Issue by MarcelCoding** [not-fl3/macroquad#348]
If you scale your windows, because you have a very high pixel density, microquad returns the x and y of the non-scaled version but uses the x and y for drawing with the scaled version.

**Comment by MarcelCoding** [comment]
If i disable high dpi it works:
```
macroquad::Window::from_config(Conf {
    sample_count: 4,
    window_title: "xxx".to_string(),
    high_dpi: false,
    ..Default::default()
}, draw());
```

But it would be cool if it also works with high dpi

**Comment by not-fl3** [comment]
https://github.com/not-fl3/macroquad/pull/343 
this did not fixed it? 

oh, I need to figure how to reproduce those high-dpi bugs myself :)

**Comment by MarcelCoding** [comment]
go the the windows settings and change the display scaling :)

**Comment by MarcelCoding** [comment]
it is possible that the bug is fixed the last release is 11 days ago and the merged pr 5 days, I am going to check the version from master

**Comment by MarcelCoding** [comment]
I just checked master, and it is fixed. 🙂 my bad
