### ISSUE TITLE
Getting a lot of "No ... function in gl.js" in the chrome developer console when building WASM

### ISSUE THREAD

**Issue by tlietz** [not-fl3/macroquad#358]
I have followed the [macroquad WASM build instructions](https://github.com/not-fl3/macroquad#wasm), and get the following results.

Warnings in Chrome developer console:
![image](https://user-images.githubusercontent.com/25965706/147846540-bb5b2f29-5fe8-4c9a-b526-49be528c3101.png)

Errors in Chrome developer console:
![image](https://user-images.githubusercontent.com/25965706/147846575-4452fa89-e14b-47e6-8cf4-a6bb9bf14c4a.png)

```
# Cargo.toml
[package]
name = "ball_bounce_macroquad"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.3"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }
```

**Comment by eboatwright** [comment]
How did you fix this?

**Comment by tlietz** [comment]
@eboatwright Sorry about the late response. I followed this thread https://github.com/not-fl3/macroquad/issues/376

**Comment by eboatwright** [comment]
Ok thanks! Yeah, it's alright :) I think I fixed my problem by updated to the newest version of Macroquad :smile:
