### ISSUE TITLE
How would I go about making an outline shader?

### ISSUE THREAD

**Issue by eboatwright** [not-fl3/macroquad#366]
I'm making a survival game in Rust, and I want to add an outline to anything the player is selecting. But, I don't want to go through all of my sprites and make an outline sprite and add a bunch of edge cases to render a different texture or source destination. So how would I go about coding a shader for it?

**Comment by adambiltcliffe** [comment]
There is an algorithm called the Jump Flood algorithm that can be useful for this. I made an example in macroquad at https://github.com/adambiltcliffe/macroquad-jfa that outlines everything in glowing colours.

**Comment by eboatwright** [comment]
That's awesome, thank you!
