### ISSUE TITLE
rand seems to always yield the same result

### ISSUE THREAD

**Issue by TheTechRobo** [not-fl3/macroquad#369]
Easy to reproduce:

```
use macroquad::rand;

fn main() {
    println!("{}", rand::gen_range(0, 5));
    println!("{}", rand::gen_range(0, 5));
    println!("{}", rand::gen_range(0, 5));
}
```

On my system, this always yields the same result: 0, 1, 4.

I even tried a `cargo clean` to no avail. Still the same result.

Is this my fault? Am I misunderstanding something? Thanks!

**Comment by not-fl3** [comment]
you probably want to seed your random numbers with some unique data, like `rand::srand(macroquad::miniquad::date::now() as _);` or something like that

**Comment by TheTechRobo** [comment]
Oh, that's not done automatically? I guess I've been spoiled by Python 😅 

I'll try that in a few hours.

**Comment by TheTechRobo** [comment]
Thanks it works!
