### ISSUE TITLE
How to draw from a batch ?

### ISSUE THREAD

**Issue by buxx** [not-fl3/macroquad#374]
Hello ! 

I'm discovering your doc to probably rewrite my game (using [coffee](https://github.com/hecrj/coffee)) with macroquad. I read example codes and documentation but didn't find answer of this question : How can I draw a batch without have a performance problem ?

![2022-01-21_13-45](https://user-images.githubusercontent.com/1104637/150529455-ce950c5f-aa1a-4542-9eac-0e2717b6bbe6.png) 
![2022-01-21_13-47](https://user-images.githubusercontent.com/1104637/150529550-b259bc47-f737-4949-8f2d-3174b4351d04.png)

Explanation : In my game, I draw a 2D top view map from a tileset.png, and I have to use a batch (built from my tileset.png) like this:

```rust
        self.tile_sheet_batch.clear();
        self.tile_sheet_batch.extend(sprites); // Where sprites is a vector of tileset.png part coordinates
        self.tile_sheet_batch.draw(&mut frame.as_target());
```

I didn't find how to make this with macroquad. I found `draw_texture`, but about draw one entire image. Other examples use tiled and its "batch" logic is probably hidden in it. 

How can I draw multiples sprites with macroquad ? Thanks for your time and I apologize if issues is not the right place for this question !

**Comment by not-fl3** [comment]
A few `draw_texture` calls from a single texture atlas should be batched automatically and works quite fast. Did you encounter some performance problems?

**Comment by buxx** [comment]
Hello, cool ! I didn't test it from now. I will do it. Thanks !

**Comment by buxx** [comment]
Hi again @not-fl3 ,

I tried it with the following code (and [graphics.png](https://user-images.githubusercontent.com/1104637/150644298-be3f9fb6-88a8-4b27-9763-dabb8280f936.png)): 

```rust
use macroquad::prelude::*;

#[macroquad::main("RollGui2")]
async fn main() {
    let tile_set = load_texture("graphics.png").await.unwrap();
    let tree_source: Rect = Rect::new(32. * 0., 32. * 2., 32., 32.);

    loop {
        clear_background(BLACK);

        for x in 0..255 {
            for y in 0..255 {
                draw_texture_ex(
                    tile_set,
                    32. * x as f32,
                    32. * y as f32,
                    WHITE,
                    DrawTextureParams {
                        source: Some(tree_source),
                        ..Default::default()
                    },
                );
            }
        }

        println!("{}", get_fps());

        next_frame().await
    }
}
```

Obtained FPS in debug mode are 8 and 60 in release mode. For 1024 * 255 call of `draw_texture_ex`, FPS are 2 in debug mode and 30 in release mode. This seems correct ?
