### ISSUE TITLE
`root_ui` windows overwriting each other

### ISSUE THREAD

**Issue by userakai** [not-fl3/macroquad#378]
I have this fn in `input.rs`

```
let BUTTON_OFFSET = 20.;
let BUTTON_SIZE = 150.;
pub fn render(&self, order: usize) -> () {
    root_ui().push_skin(skin);
    root_ui().window(
	hash!(),
	vec2(
		BUTTON_OFFSET,
		BUTTON_OFFSET + ((order as f32) * BUTTON_SIZE),
	),
	vec2(BUTTON_SIZE, BUTTON_SIZE),
	|ui| {
		if widgets::Button::new("").position(vec2(-1., -1.)).ui(ui) {
			println!("hello");
		}
	},
    );
    root_ui().pop_skin();
}
```

and call it in a loop in `main.rs`, in order to create multiple windows with different buttons, with their vertical position variating according to `order`. Although, it renders every button in the coordinates of the first rendered window (order = 0). If I try to avoid rendering the first, every button renders in the coordinates of the second window. 

It looks like the first rendered window decides the coordinates for all the others. Why is that?

**Comment by not-fl3** [comment]
windows should have a unique id. You can add a `id` argument, like this: `render(&self, id: usize,..)`
and use it as `window(hash!(id), ..` or just `window(id, ..`
