### ISSUE TITLE
[Question] How to limit FPS?

### ISSUE THREAD

**Issue by alexmozaidze** [not-fl3/macroquad#380]
I want to test wether delta time in my game works as expected and want to test the game on different fps, but there's no function to do that, can you add one, please? It's not even necessary for it to work on all platforms, just desktop would be nice, for debugging and stuff.

**Comment by buxx** [comment]
Hello @alexmozaidze , do https://docs.rs/macroquad/latest/macroquad/time/index.html is usefurl for you ?

**Comment by alexmozaidze** [comment]
Time module is useful for counting fps but not for limiting it.

**Comment by buxx** [comment]
My personal usage of this module is to make a sleep according to previous frame duration. By targeting my desired fps.

**Comment by alexmozaidze** [comment]
I don't know how to do that, I couldn't get any examples on the internet to work. Can you show an example of how to do that?

**Comment by buxx** [comment]
There is an example : 

```rust
let minimum_frame_time = 1. / 60.; // 60 FPS
let frame_time = get_frame_time();
println!("Frame time: {}ms", frame_time * 1000.);
if frame_time < minimum_frame_time {
    let time_to_sleep = (minimum_frame_time - frame_time) * 1000.;
    println!("Sleep for {}ms", time_to_sleep);
    std::thread::sleep(std::time::Duration::from_millis(time_to_sleep as u64));
}
```

But this is not wasm compatible :( (std::thread cannot be used with wasm).

Anyone know how to make a sleep with wasm ?

**Comment by buxx** [comment]
I asked some information about sleep and wasm. There is the response I got : 

You can't create a synchronous one, but to make an async one do this:

1. In your Javascript code declare this function: 

```rust
export function js_sleep(ms) {
    let id;
    const promise = new Promise(resolve => id = setTimeout(resolve, ms));
    return [promise, id];
}
export function clear_timeout(x) {
    clearTimeout(x)
}
```


2. Write this Rust glue code: 

```rust
#[wasm_bindgen(module = "/path/to/the/module.js")]
extern "C" {
    fn js_sleep(millis: u32) -> js_sys::Array;
    fn clear_timeout(id: i32);
}

pub async fn sleep(time: Duration) {
    let millis = u32::try_from(time.as_millis()).unwrap_or(u32::MAX);
    let tuple = js_sleep(millis);
    let promise = Promise::from(tuple.get(0));
    let id = tuple.get(1).as_f64().unwrap() as i32;
    struct Sleep {
        future: JsFuture,
        id: i32,
    }
    impl Future for Sleep {
        type Output = ();
        fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
            Pin::new(&mut self.future).poll(cx).map(|res| { res.unwrap(); })
        }
    }
    impl Drop for Sleep {
        fn drop(&mut self) {
            clear_timeout(self.id);
        }
    }
    Sleep {
        future: JsFuture::from(promise),
        id,
    }
    .await
}
```


From then on you should be able to call sleep in Rust

**Comment by alexmozaidze** [comment]
With all that info, I now realize that having a function to limit fps is pretty limiting since it would take away the control from the developer. I'll change the title so it's easier to find by others. Thank you for helping me!

**Comment by DaLynX** [comment]
Hi, I am trying to achieve this but am still missing some bits like where to put this js code and how to regenerate a fully working `gl.js` file. Would you have some advice for that?

Also, don't you think this could be integrated in macroquad? Some developers like me 🙃 would be interested in having a _sleep_ function.

**Comment by buxx** [comment]
I'm interested too. I tried by adding a sleep fonction (like in previous example) but I failed. @not-fl3 I have a question : Use a `async_std::task::sleep` could be a solution ?

**Comment by DaLynX** [comment]
It seems that's not supported in wasm yet: https://github.com/async-rs/async-std/issues/220

**Comment by DaLynX** [comment]
Right, I was trying to use `thread::sleep` so of course it didn't work but using `macroquad::time::get_time()` in an `if` block for my update code works fine. Thanks for pointing me to the right direction!

**Comment by des54321** [comment]
@not-fl3 

Is there a reason macroquad doesn't seem to give a way to change the fps above 60?

**Comment by brettchalupa** [comment]
Curious about the question above ☝️ 

In theory, I don't see any reason why `target_fps` or `max_fps` couldn't be configured

**Comment by GustavoRamos112** [comment]
````rust
use macroquad::prelude::*;

fn window_conf() -> Conf {
    Conf {
        window_title: "Uncap fps".to_owned(),
        sample_count: 0,
        platform: miniquad::conf::Platform {
          swap_interval: Some(0), // <- this line: 0: unlimited fps, 1: 60 fps, 2: 30 fps, 3: 15 fps
          ..Default::default()
        },
        window_resizable: true,
        window_width: 800,
        window_height: 600,
        ..Default::default()
    }
}

#[macroquad::main(window_conf)]
async fn main() {
  //? main loop
  loop {
    clear_background(BLACK);

    draw_text(
      format!("{:.4} s/{:.0} fps", get_frame_time(), 1.0/(get_frame_time() as f32)).as_str(), 
      0.0, 13.0, 20.0, WHITE,
    );

    next_frame().await
  }
}
````

**Comment by afrizalhasbi** [comment]
Linking [#749](https://github.com/not-fl3/macroquad/issues/749#issuecomment-4775279310), the `swap_interval` method is not reliable across machines and platforms and you will get a wide fps distribution. Using this method I got a near exact off-by-1 fps:

```rust
    let fps_target = 60.0;
    let frame_dur = Duration::from_secs_f64(1.0 / fps_target);
    let mut next_tick = Instant::now();

    loop {
        // game logic ...

        next_tick += frame_dur;
        let now = Instant::now();
        if next_tick > now {
            spin_sleep::sleep(next_tick - now); // spin_sleep crate; might be more reliable than std::thread::sleep
        } else {
            next_tick = now; // catch up after a slow frame
        }

        next_frame().await;
    }
```

The fps is reliably around 59-60 with this method, at least on my linux machine.

So far, I have not experienced any blocking problems by the sleep.

May not work in WASM, haven't tried.

**Comment by GustavoRamos112** [comment]
> Linking [#749](https://github.com/not-fl3/macroquad/issues/749#issuecomment-4775279310), the `swap_interval` method is not reliable across machines and platforms and you will get a wide fps distribution. Using this method I got a near exact off-by-1 fps:
> 
>     let fps_target = 60.0;
>     let frame_dur = Duration::from_secs_f64(1.0 / fps_target);
>     let mut next_tick = Instant::now();
> 
>     loop {
>         // game logic ...
> 
>         next_tick += frame_dur;
>         let now = Instant::now();
>         if next_tick > now {
>             spin_sleep::sleep(next_tick - now); // spin_sleep crate; might be more reliable than std::thread::sleep
>         } else {
>             next_tick = now; // catch up after a slow frame
>         }
> 
>         next_frame().await;
>     }
> The fps is reliably around 59-60 with this method, at least on my linux machine.
> 
> So far, I have not experienced any blocking problems by the sleep.
> 
> May not work in WASM, haven't tried.

According to what I researched, apparently that option is inherited directly from OpenGL. If the drivers are compatible with it, it should work. Likewise, I use the `swap_interval` method for debugging purposes, since macroquad on my PC automatically limits me to 60 FPS, which limits my understanding of the optimization of what I'm working on. So I set `swap_interval: Some(0)` to remove the FPS cap and increase them as much as possible.

For a release build, I think your proposal is the most convenient, since it forces a sleep (although, as you say, it steals 1 frame) and this is compatible with Rust's standard library, so it should work in WASM (and if it doesn't, it's just a matter of changing the sleep to one compatible with it).

Conclusion: Using `swap_interval: Some(0)` removes (at least on my machine) the FPS limit, which facilitates application optimization.
