### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by optozorax** [not-fl3/macroquad#382]
Hi! Could you please release a new version of the `macroquad` with `miniquad = { version = "=0.3.0-alpha.43" }`. This dependency is required in the `egui-miniquad` ([source](https://github.com/not-fl3/egui-miniquad/blob/master/Cargo.toml#L23)). And because of this `egui-macroquad` didn't work with the latest `macroquad` ([issue](https://github.com/optozorax/egui-macroquad/issues/14)).

**Comment by jackfranklin** [comment]
@optozorax I think the release yesterday might enable this now? I'm not 100% clear but I think you could now bump a new egui-macroquad and it should play nicely.

**Comment by optozorax** [comment]
Yeah, thanks.
