### ISSUE TITLE
Create file to persist state in Android

### ISSUE THREAD

**Issue by seguidor777** [not-fl3/macroquad#383]
Hi,

First of all, thanks to everyone who supports this amazing project.
I just created a game and built it for Android. I can read asset files but I am looking how to create a file
in order to save the game state, does anyone have an idea how to do it?

**Comment by MaxRang** [comment]
I was trying to do the same thing, I found this crate which provides the functionality you're looking for.

https://crates.io/crates/quad-storage

**Comment by seguidor777** [comment]
Cool, thanks @MaxRang for sharing, I'll give it a try
