### ISSUE TITLE
draw_rectangle is really slow.

### ISSUE THREAD

**Issue by eboatwright** [not-fl3/macroquad#399]
I'm making a little ANSI rendering API / engine thing for my games. (ANSI is a form of ASCII :)), and for each tile, I'm rendering a rectangle (using draw_rectangle()) to act as a background for each tile, and I'm also drawing the tile from an image. When rendering a whole screen of tiles, it lags down to 5 fps. So, I started investigating. I found the culprit, when I comment out the background drawing code. (Here it is if you're wondering)
```rs
// Draw the background
draw_rectangle(
	position.x * 9.0,
	position.y * 16.0,
	9.0,
	16.0,
	self.bg_color,
);
```
When I comment out this code, it runs at 60 fps.

P.S. I'm on the latest version of Macroquad, (0.3.15) and on Pop! OS 21.04 (An Ubuntu based distro)

**Comment by not-fl3** [comment]
I would recommend drawing all the letters first and then draw all the rectangles. This way its going to be just 2 material switches instead of Number Of Character material switches

**Comment by eboatwright** [comment]
*Ohh*. Alright, I'll refactor my code :sweat_smile:
