### ISSUE TITLE
Multiple sound channels?

### ISSUE THREAD

**Issue by eboatwright** [not-fl3/macroquad#402]
Is there a way to play 2 sounds at the same time without them queuing up?

**Comment by p-ruszkowski** [comment]
@eboatwright what do you mean about queuing up sounds? You should be able to play multiple sound at once with play_sound and play_sound_once functions.

**Comment by eboatwright** [comment]
This must have been a problem with an older macroquad version. I just tried it with 0.3.24 and it worked fine. Sorry to bother anyone!
