### ISSUE TITLE
Error compiling v0.3.19

### ISSUE THREAD

**Issue by ccie18473** [not-fl3/macroquad#425]
It's the first time I'm using macroquad,
I used ggez and gwg in the past. I get this error when trying to compile my first example:
####################################
   Compiling macroquad v0.3.19 (/home/amsoares/Programming/rust/macroquad-master)
error[E0107]: this struct takes 0 lifetime arguments but 2 lifetime arguments were supplied
   --> src/window.rs:35:41
    |
35  |     pub quad_context: &'a mut miniquad::Context<'static, 'static>,
    |                                         ^^^^^^^------------------ help: remove these generics
    |                                         |
    |                                         expected 0 lifetime arguments
    |
note: struct defined here, with 0 lifetime parameters
   --> /home/amsoares/.cargo/registry/src/github.com-1ecc6299db9ec823/miniquad-0.3.8/src/graphics.rs:632:12
    |
632 | pub struct GraphicsContext {
    |            ^^^^^^^^^^^^^^^

error[E0107]: this struct takes 0 lifetime arguments but 2 lifetime arguments were supplied
   --> src/lib.rs:153:19
    |
153 |     quad_context: QuadContext<'static, 'static>,
    |                   ^^^^^^^^^^^------------------ help: remove these generics
    |                   |
    |                   expected 0 lifetime arguments
    |
note: struct defined here, with 0 lifetime parameters
   --> /home/amsoares/.cargo/registry/src/github.com-1ecc6299db9ec823/miniquad-0.3.8/src/graphics.rs:632:12
    |
632 | pub struct GraphicsContext {
    |            ^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0107`.
####################################
My environment:
####################################
amsoares@ubuntu:macroquad-master$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/amsoares/.rustup

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
wasm32-wasi
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.61.0 (fe5b13d68 2022-05-18)
####################################
Thanks

**Comment by ccie18473** [comment]
I see that miniquad was changed:
Remove <'a, 'b> from Context definition
Maybe I just need to wait.

**Comment by sloganking** [comment]
https://i.imgur.com/rjftwRO.png

I just starting seeing this on GitHub actions. And I get this locally after running ``cargo update`` which updated these packages

![](https://i.imgur.com/rjftwRO.png)

I assume this means there is a bug in  ``miniquad v0.3.8``

**Comment by sloganking** [comment]
@ccie18473 you can fix this in the meantime by telling your project to use an old miniquad version via

``cargo update -p miniquad --precise 0.3.7``

**Comment by ccie18473** [comment]
Thanks @sloganking It worked the way you mentioned.

**Comment by not-fl3** [comment]
oh, thanks for report, there is a typo in macroquad's cargo.toml - it should be "version = "=0.3.7"," instead of just "0.3.7". Feel free to make a PR, but the real fix updating macroquad for the latest miniquad is on the way!

**Comment by sloganking** [comment]
Thanks. See #426 for the pull request. However per [semantic versioning](https://semver.org/) wouldn't going from ``0.3.7`` to ``0.3.8`` indicate a backwards compatible, non breaking change? I'm not sure how many other projects rely on miniquad, But I'd consider yanking miniquad ``0.3.8`` if it's not backwards compatible. As other projects relying on it might run into the same issue.

**Comment by duckfromdiscord** [comment]
I cannot use macroquad with ios because this issue is introduced in 0.3.8 and never fixed, and `miniquad::native::apple` does not exist in 0.3.7
