### ISSUE TITLE
High CPU resources in Window 10.

### ISSUE THREAD

**Issue by kakoeimon** [not-fl3/macroquad#43]
When I run the texture example I get 17-19% CPU resources.
That's really high.

My machine:
Intel i7-8750H
NVIDIA GeForce GTX 1060

As reference in Discord I had a discussion about the issue and I had a report that in Linux it is around 2% and that sounds about right.

**Comment by Pebaz** [comment]
@kakoeimon Not sure if this is helpful info, but when I run it on the specs below, it caps out at about 3.5% CPU resources on my machine:
* Windows 10 x64
* Intel i7 7500U @ 2.70GHz
* Intel HD Graphics 620
