### ISSUE TITLE
Is it possible to make `Vec2::new` and friends const?

### ISSUE THREAD

**Issue by Diegovsky** [not-fl3/macroquad#434]
There are constants such as `ONE`, `ZERO` and unit constants so I don't think it's impossible.

I did a single search with the terms "vec" and "const" but didn't find anything related but I hope this isn't a duplicate :)

**Comment by Diegovsky** [comment]
Thanks, I didn't think of it!

**Comment by not-fl3** [comment]
note that macroquad's `math` is re-exported `glam-rs`
