### ISSUE TITLE
prevent_quit ignored

### ISSUE THREAD

**Issue by f1nsternacht** [not-fl3/macroquad#449]
Running the exit_dialog.rs example the window closes without showing the dialog when clicking the close window button.

OS: Manjaro Linux x86_64
Rust: stable-x86_64-unknown-linux-gnu (default)
  rustc 1.62.1 (e092d0b6b 2022-07-16)

**Comment by not-fl3** [comment]
Should be fixed by [84b2f05ac132bb108dcdf6d25fddd084ecfb78b0](https://github.com/not-fl3/miniquad/commit/4766ee4ee07a9e3b75d60d4e791d40cf436f8a21)
