### ISSUE TITLE
How to include resources into apk?

### ISSUE THREAD

**Issue by mrlogick** [not-fl3/macroquad#45]
I successfully created the apk for Android. But how can I include a png into it? When I compile the example "texture.rs" on my pc at runtime it finds "ferris.png", but on Android I need to include this image into the apk (in the right path).
Maybe this is not the right place to ask, so where can I learn the stuff about making the apk? Now I simply use this command:
`$ docker run --rm -v $(pwd)":/root/src" -w /root/src notfl3/cargo-apk cargo apk build --example texture`

**Comment by not-fl3** [comment]
Hi! 

Since macroquad `v0.3.0-alpha.1` you can add 

```
[package.metadata.android]
assets = "path/to/assets"
```

to your Cargo.toml and use `load_file`/`load_texture` as usual!
