### ISSUE TITLE
Transform Space

### ISSUE THREAD

**Issue by pedrotrschneider** [not-fl3/macroquad#450]
Is there a way to apply transformations to the space, such as translation, rotation and zoom? For instance, I would like to make the origin of the world the center of the screen instead of the top-left corner. Other things I would like to achieve are rotating space around the origin and zoom in each axis separately. I understand this could be achieved in 3d by using cameras, but this seems a bit overkill for 2d applications, and I didn't manage to make it work either way.
Is there currently a way to do that? I'm on version ```0.12.2```.

**Comment by not-fl3** [comment]
Note that the latest version is `0.3.*`, we never reached `0.12` :) 

For the transforms: this example might help: https://github.com/not-fl3/macroquad/blob/master/examples/tree.rs#L12

**Comment by pedrotrschneider** [comment]
Thanks! I accidentally got the version of another crate I was using. Sorry for that! I am on the correct version.
Thanks for the response! It did help me fix it.
