### ISSUE TITLE
Per pixel operations

### ISSUE THREAD

**Issue by pedrotrschneider** [not-fl3/macroquad#455]
I was wondering what would be the best way to perform per-pixel operations with macroquad. The way I'm currently doing it is by creating an Image outside the loop, manipulating it inside the loop, and each frame creating a new Texture2D from that Image, and drawing the texture to the screen, but this seems cumbersome (especially the part where I create a new Texture2D every frame).

I'm doing it this way because I didn't find a way to render an Image to the screen without converting it to a Texture2D first, and I assume there is no way to manipulate a Texture2D without a shader since it is in GPU memory. I also need to achieve this without the use of shaders, because the manipulations I need are such that I can't / don't want to do using shaders.

I also didn't find a way to manipulate the screen's pixels directly from code.

So, what is the intended way to something like this?

**Comment by Im-Oab** [comment]
Have you looked into this `game of life` example? It uses `texture.update()` for updating texture using the image, and It keeps manipulating the same `Image` over and over.

https://github.com/not-fl3/macroquad/blob/master/examples/life.rs

**Comment by pedrotrschneider** [comment]
Oh, that's exactly what I was looking for! I tested it and performance doesn't seem to have improved by the change from creating a new ```Texture2D``` and updating an already existing one, but it looks cleaner to me. Thanks!
