### ISSUE TITLE
Problems running example code

### ISSUE THREAD

**Issue by edilsonjmavone** [not-fl3/macroquad#457]
I'm still learning rust and this library, i only copied the code from the docs: 
```rs
use macroquad::prelude::*;

#[macroquad::main("BasicShapes")]
async fn main() {
    loop {
        clear_background(RED);

        draw_line(40.0, 40.0, 100.0, 200.0, 15.0, BLUE);
        draw_rectangle(screen_width() / 2.0 - 60.0, 100.0, 120.0, 60.0, GREEN);
        draw_circle(screen_width() - 30.0, screen_height() - 30.0, 15.0, YELLOW);
        draw_text("HELLO", 20.0, 20.0, 20.0, DARKGRAY);

        next_frame().await
    }
}
```
And installed the library and its dependencies, 
But when do `cargo run` i get this error : `
X Error of failed request:  GLXBadFBConfig
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  60
  Current serial number in output stream:  59
 `
I don't know if this error has to do with rust or macroquad

**Comment by not-fl3** [comment]
looks like an incompatible GL version, right now the minimal one is 3.2

Does other gpu accelerated programs works? `glxgears`/`glxinfo`?

**Comment by edilsonjmavone** [comment]
yes they work
And you are right, it's my GL version 
`$glxinfo | grep "OpenGL version"`  returned  `OpenGL version string: 1.4 Mesa 18.0.5`
i don't know how to solve this, but anyways thanks for the help
