### ISSUE TITLE
Error handling for load_texture

### ISSUE THREAD

**Issue by tatref** [not-fl3/macroquad#46]
Hi,

There's a few places where the code can panic:
https://github.com/not-fl3/macroquad/blob/31cff5d89ed17a6c83f39cf6568348dab25145dc/src/texture.rs#L11

Also in quad-gl:
https://github.com/not-fl3/quad-gl/blob/3e0bbc0e36fd960c4e99a611a1d94b5d4bb9523e/src/lib.rs#L573
https://github.com/not-fl3/quad-gl/blob/3e0bbc0e36fd960c4e99a611a1d94b5d4bb9523e/src/lib.rs#L577

Could it be possible to return a ```Result``` instead?
I believe there's not error type yet, so we'd need to define this first?

**Comment by optozorax** [comment]
This is done in https://github.com/not-fl3/macroquad/pull/193
