### ISSUE TITLE
Incorrect UI rendering on MacOS built-in Retina display

### ISSUE THREAD

**Issue by afischl** [not-fl3/macroquad#464]
I just copied the [UI example code](https://github.com/not-fl3/macroquad/blob/master/examples/ui.rs) and executed it.

The UI example looks fine both on my Linux machine, and on my MacBook Pro (2019, the ones with the touch bar) as long as I show it on my lower-resolution external monitor (2560x1440):
![macroquad-ui-ok](https://user-images.githubusercontent.com/4990287/183697884-0e389586-df94-4d3e-8780-4e1afffeb5ab.png)

However, when the UI example is on the MacBooks own display (the Retina display), it looks like this:
<img width="912" alt="macroquad-ui-broken" src="https://user-images.githubusercontent.com/4990287/183698063-1cc3b1bc-e434-4f53-84bc-65ce7679dc97.png">

Note that the contents of all three windows is gone (and the window titles' positions are slightly off).

**Comment by afischl** [comment]
Thanks for the quick reply! No worries, there's no pressure from my side for a quick fix.

If there is a way to provide you with some debug infos from an actual high-dpi machine (despite me being a Macroquad-n00b who started off learning a bit Rust in the evenings) let me know.

**Comment by nezvers** [comment]
I can report the same problem on Windows with 4k display, 150% scaling

**Comment by afischl** [comment]
This has been a significant improvement but unfortunately we're not quite there yet. I've described everything in detail in a new ticket: #530
