### ISSUE TITLE
Macroquad fps is at 1

### ISSUE THREAD

**Issue by Dequog** [not-fl3/macroquad#468]
Hello I am creating a game with macro quad and when I run `get_fps()` I get 1. I don't know why this is happening will you please help.

**Comment by eboatwright** [comment]
Where is your source code?

**Comment by Dequog** [comment]
I found some performance optimizing code and that seems to help.

[profile.dev.package.'*']
opt-level = 3

**Comment by eboatwright** [comment]
Ah, alrighty then!
