### ISSUE TITLE
Screen size incorrect before calling `next_frame`

### ISSUE THREAD

**Issue by n0s4** [not-fl3/macroquad#469]
I want to calculate an initial position based on the screen size before the game loop, however calling `screen_width` / `screen_height` before the first `next_frame` call always gives me 800x600, regardless of the actual window size.

code to reproduce:
```rust
use macroquad::prelude::*;

#[macroquad::main("test")]
async fn main() {
    println!("size before: {}x{}", screen_width(), screen_height());
    next_frame().await;
    println!("size after: {}x{}", screen_width(), screen_height());
}
```
gives:
```
size before: 800x600
size after: 1342x717 (actual size)
```

Is there a workaround for this?

**Comment by not-fl3** [comment]
I've seen this problem before and I do not really know how to fix it :( 

The problem here - window manager actually resizes the window. It really is 800x600 on the first frame and then the window manager decides that it wants to resize it. 

I think the only solution - accept it and be aware that the window might resize at any moment :(

**Comment by n0s4** [comment]
OK, thanks. So I could just have an initial `next_frame().await;` outside the loop before I capture the screen dimensions?

**Comment by not-fl3** [comment]
I would recommend making the logic aware of possible window size changes.

**Comment by kacper-cholewinski** [comment]
You could define screen size (and other things) in Conf struct.
`#[main(window_config)]`
`pub fn window_config() -> Conf {
  Conf {
    window_title: "Space Invaders".to_owned(),
    window_width: 450,
    window_height: 800,
    ..Default::default()
  }
}`

**Comment by n0s4** [comment]
I've reworked the logic to not be dependent on window size which is a lot better. Seeing as there isn't anything really to "fix" I'll close this now. Thanks.
