### ISSUE TITLE
Artifacts on rectangle/texture edges

### ISSUE THREAD

**Issue by RybekU** [not-fl3/macroquad#47]
# Issue:
When placed on non-integer coordinates both drawn rectangles (I suspect this applies to all shapes) and textures (in `FiterMode::Nearest` where it shouldn't be the case!) get visible artifacts.

Example for rectangle:
![obraz](https://user-images.githubusercontent.com/45723292/94832957-d8e6f500-040e-11eb-8e79-4dcda3236b36.png)
Example for a texture:
![obraz](https://user-images.githubusercontent.com/45723292/94833432-688ca380-040f-11eb-96d9-5bfc3e5ce2a0.png)
Correctly rendered texture by attaching a 1px transparent border to it:
![obraz](https://user-images.githubusercontent.com/45723292/94833535-85c17200-040f-11eb-8257-259ec35bb5e7.png)
# Reproduction:
Bug can be reproduced by putting the following file in the examples folder and running `cargo run --example filter_err`:
https://paste.ofcode.org/MuS8ezGpuwvPg2BxM6FBRq
Additional instructions inside.
To test the version with file download these 2 additional images and put them in the examples folder:
(borderless.png)
![borderless](https://user-images.githubusercontent.com/45723292/94833677-b2758980-040f-11eb-84bd-7fe8d57e4282.png)
(border.png)
![border](https://user-images.githubusercontent.com/45723292/94833683-b30e2000-040f-11eb-81c4-d0714f41b366.png)
# Performed tests:
- rounding to integer coordinates [fixes the issue, but not a valid solution with a zoom]
- using `draw_texture_ex` to explicitly set the drawn area [doesn't work]
- adding border to the image and always drawing the 1px border [fixes the issue, hints at possible off-by-one error in the source code and can't be used for rectangles and other provided shapes]
# Specs:
Windows 10, newest version of stable Rust, branch 0.3 of macroquad

**Comment by RybekU** [comment]
Drewol#6054 on discord stated the issue goes away when you force disable AA in driver settings, but that isn't an option when distributing a game.
Otherwise if your window uses resolution being multiple of a base (say, 320x180) you can try this:
The coordinates have to be aligned with pixel grid of the current resolution. Function such as the one below can be used for the conversion.
```rust
pub fn align2subpixels(num: f32, game_scale: f32) -> f32 {
    let frac = num.fract();
    let num = num.trunc();
    num + (frac * game_scale).trunc() / game_scale
}
```
The function works the same way as the common "clipping to integer coordinates", but takes the upscaled resolution into account.

**Comment by ManicMarrc** [comment]
Sorry to reply to this old issue, but I'm currently having the same problem. I don't get how to use the given function by @RybekU. Can you give me a small example please?

**Comment by RybekU** [comment]
> Sorry to reply to this old issue, but I'm currently having the same problem. I don't get how to use the given function by @RybekU. Can you give me a small example please?

Remember to apply it to both camera's position and all sprites.
```rust
// source position
let pos = vec2(5.6316, 8.131);
// we will assume each pixel is actually a 3x3 square of pixels (game_scale of 3)
let aligned_pos = (align2subpixel(pos.x, 3.), align2subpixel(pos.y, 3.));
```
