### ISSUE TITLE
Update to the latest miniquad

### ISSUE THREAD

**Issue by optozorax** [not-fl3/macroquad#475]
Hi! Could you please update the `macroquad` to use the latest `miniquad` 0.3.12?

**Comment by EvoTeamDevelop** [comment]
@optozorax seems we have good news, macroquad was updated to support the latest miniquad version, which is even 0.3.13 :)

**Comment by alexswan10k** [comment]
Hi,

I am not having much luck with this. Would you be able to specifically recommend a pair which works? I am trying 
macroquad: 0.3.24
bundle:
```
    <!-- <script src="https://not-fl3.github.io/miniquad-samples/mq_js_bundle_0.3.0.js" ></script> -->
    <!-- <script src="https://not-fl3.github.io/miniquad-samples/mq_js_bundle_0.3.1.js" ></script> -->
    <script src="https://not-fl3.github.io/miniquad-samples/mq_js_bundle_0.3.23.js" ></script>
    <!-- <script src="https://not-fl3.github.io/miniquad-samples/mq_js_bundle_0.3.8.js" ></script> -->
```

All combinations seem to fail with the following error
```
WASM failed to load, probably incompatible gl.js version
TypeError: WebAssembly.instantiate(): Import #0 module="__wbindgen_placeholder__" error: module is not an object or function
```

I have repeated the same with 0.3.21, and 0.3.20 with the same effect. Annoyingly I had this working at one point, but presumably, the dependencies have changed on the remote. Ideally I would like to lock the js side down so the build is repeatable. I may have been using ```https://not-fl3.github.io/miniquad-samples/mq_js_bundle.js```

Any help would be appreciated.

**Comment by not-fl3** [comment]
> __wbindgen_placeholder__

this error indicates that you are using websys as a dependency
websys assumes building with a third-party CLI tool, wasm-bindgen

setting up wasm-bindgen is quite complicated, I never did it myself so can't really give any advices here, but this comment might help: https://github.com/not-fl3/macroquad/issues/212#issuecomment-835276147

**Comment by alexswan10k** [comment]
Thanks for getting back.

Interesting... I see your point, so I checked to see what my build script looked like, but it definitely does not call onto wasm-bindgen. It calls the following:

```
cargo build --target wasm32-unknown-unknown --release
```

There is also no reference to wasm-bindgen in my cargo.toml file.

I followed the wasm bootstrap instructions here https://github.com/not-fl3/macroquad#wasm

The assembly is then invoked after the mq_js bundle:
```
<script>load("compiledasset.wasm");</script>
```

Perhaps there is something related not set up correctly?

**Comment by not-fl3** [comment]
one of you dependencies depend on something that assumes using of wasm-bindgen

**Comment by alexswan10k** [comment]
Ahh yes indeed. I found a transitive ```chrono``` reference with default features turned on. Turns on this makes a reference to wasm-bindgen. 

Removing this worked. Many thanks!

**Comment by optozorax** [comment]
New version work, thanks.

**Comment by ierehon1905** [comment]
For someone also struggling with error like

```
Import #90 module="__wbindgen_placeholder__" error: module is not an object or function
```

I tracked down the library that used `wasm-bindgen` and restricted to only needed features (in my case: `lib:image feature:png`)

```toml
image = { version = "0.24.6", features = ["png"], default-features = false }
```
