### ISSUE TITLE
Update `js/mq_js_bundle.js` for file drop

### ISSUE THREAD

**Issue by ShuP1** [not-fl3/macroquad#479]
not-fl3/miniquad#275 adds file drop with corresponding imports in `js/gl.js` but macroquad `js/mq_js_bundle.js` is outdated

**Comment by bbstilson** [comment]
This might be related to the error I'm getting:

![image](https://user-images.githubusercontent.com/7949037/187301564-6875d6ae-bc58-4271-894e-b2b912182966.png)

[From my index.html](https://github.com/bbstilson/asteroids-rs/blob/main/index.html)

**Comment by ShuP1** [comment]
Fixed by not-fl3/macroquad@51a7be9
