### ISSUE TITLE
Compile exception when combining bevyECS with macroquad

### ISSUE THREAD

**Issue by nurmatthias** [not-fl3/macroquad#502]
Hi,

I have setup the simplest project we can generate with cargo and added the dependencies macroquad and bevy (without the default featureset):

[package]
name = "test_macroquad_bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version= "0.8.1", default-features = false }
macroquad = "0.3.24"

When I try _cargo run_ then the compiler is complaining about glam dependency:

error[E0119]: conflicting implementations of trait `reflect::Reflect` for type `glam::BVec3`
   --> C:\Users\nurMatthias\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_reflect-0.8.1\src\impls\glam.rs:245:1
    |
98  | / impl_reflect_struct!(
99  | |     #[reflect(Debug, PartialEq, Default)]
100 | |     struct BVec3 {
101 | |         x: bool,
...   |
104 | |     }
105 | | );
    | |_- first implementation here
...
245 |   impl_reflect_value!(BVec3A(Debug, PartialEq, Default));
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `glam::BVec3`
    |
    = note: this error originates in the macro `impl_reflect_value` (in Nightly builds, run with -Z macro-backtrace for more info)

Do you have an idea how I can use the bevyECS (only the ecs part without the rendering)?

[test_macroquad_bevy.zip](https://github.com/not-fl3/macroquad/files/9714485/test_macroquad_bevy.zip)

**Comment by Mifom** [comment]
Hi, @nurmatthias . You can use Bevy ECS through the `bevy_ecs` crate.

So the code will look like:
```rust
use bevy_ecs::prelude::*;
use macroquad::prelude::*;

#[derive(StageLabel)]
pub enum Label {
    One,
};

#[macroquad::main("Test macroquad bevy")]
async fn main() {
    let mut world = World::new();

    // Initialize some resources
    // world.insert_resource(...);

    let mut schedule = Schedule::default();

    schedule.add_stage(
        Label::One,
        SystemStage::parallel()
            // Add systems
            //.with_system(...),
    );

    loop {
        schedule.run(&mut world);

        next_frame().await;
    }
}
```

**Comment by nurmatthias** [comment]
Hi,
thanks for pointing that out. I had ignored that I can use the ecs crate directly.
