### ISSUE TITLE
macroquad::text::TextDimensions should implement Debug

### ISSUE THREAD

**Issue by rope-hmg** [not-fl3/macroquad#503]
I want to derive `Debug` for my struct, but I can't.

Is there any reason for not deriving `Debug` for `TextDimensions`?

**Comment by rope-hmg** [comment]
Also `Clone` and `Copy`. Looks like the `TextDimensions` struct doesn't derive anything. As a workaround I've made my own version of it that does derive these things and I've implemented `From` for it.

**Comment by not-fl3** [comment]
Sure, feel free to submit a PR!

**Comment by rope-hmg** [comment]
https://github.com/not-fl3/macroquad/pull/504
