### ISSUE TITLE
HTML for UI.

### ISSUE THREAD

**Issue by Evgene-Kopylov** [not-fl3/macroquad#508]
An idea about having UI through regular `HTML`. It is nothing more common then this.

Additionally that would make any integration ease.

Идея в том чтобы строить интерфейс с помощью инструментов, которые для этого гораздо лучше подходят. Это разгрузит движок, и облегчит взаимодействие с веб-приложениями.

**Comment by not-fl3** [comment]
Way out of macroquad scope :)
