### ISSUE TITLE
Wrong char send to the "char_event" function of EventHandler when targetting WASM

### ISSUE THREAD

**Issue by FaunKr** [not-fl3/macroquad#512]
When the "ä" key is pressed the `char_event` function of an EvenHandler gets called with `\'` instead of the expected `ä`. 

This doesn't affect the other umlauts and doesn't happen when targeting Android, Linux and Windows.

I took a look at the miniquad implementation and i'm not sure how to fix it.

Tested with this code:
```rust
use macroquad::miniquad::{EventHandler, Context, KeyMods};
use macroquad::input::utils::{register_input_subscriber,repeat_all_miniquad_input};
use macroquad::prelude::{KeyCode, debug, next_frame};
use macroquad::window::Conf; 



pub struct KeyboardSubscriber{

    subscriber_id: usize,
}

impl KeyboardSubscriber{
    pub fn new() -> Self{
         
        Self{
            subscriber_id: register_input_subscriber()
        }
    }

    pub fn update(&mut self){
        
        repeat_all_miniquad_input(self, self.subscriber_id); 
    }
}

impl EventHandler for KeyboardSubscriber{
    fn update(&mut self, _ctx: &mut Context) {}

    fn draw(&mut self, _ctx: &mut Context) { }
    fn char_event(&mut self, _ctx: &mut Context, _character: char, _keymods: KeyMods, _repeat: bool) {
        
        debug!("{:?}",_character);
    }
}



fn window_conf() -> Conf {
    Conf {
        window_title: "TEST".to_owned(),
        ..Default::default()

    }
}



 
#[macroquad::main(window_conf)]
async fn main() {

    let mut keyboard_subscriber = KeyboardSubscriber::new();
    loop{ 
         keyboard_subscriber.update();
        
        next_frame().await; 
    } 
}
```

**Comment by FaunKr** [comment]
I deminified `mq_js_bundle.js` and was able to fix it by changing a line in `into_sapp_keycode(e)`

```rust
        case "Quote":
            return 39;
```
to
```rust
        case "Quote":
            return 222;
```


I would create a mergerequest, but i'm not sure how to proceed, because the [readme](https://github.com/not-fl3/macroquad/blob/master/js/README.md) on how to recreate the file seems to be outdated.

Should i just directly edit the minified file and the corresponding [file](https://github.com/not-fl3/miniquad/blob/master/js/gl.js#L434) in the miniquad repo and create a merge request for both?

**Comment by not-fl3** [comment]
> I deminified `mq_js_bundle.js` and was able to fix it by changing a line in `into_sapp_keycode(e)`
> 
> ```rust
>         case "Quote":
>             return 39;
> ```
> 
> to
> 
> ```rust
>         case "Quote":
>             return 222;
> ```
> 
> I would create a mergerequest, but i'm not sure how to proceed, because the [readme](https://github.com/not-fl3/macroquad/blob/master/js/README.md) on how to recreate the file seems to be outdated.
> 
> Should i just directly edit the minified file and the corresponding [file](https://github.com/not-fl3/miniquad/blob/master/js/gl.js#L434) in the miniquad repo and create a merge request for both?
> 
> Edit;
> 
> it would also be good if someone could test that it doesn't break anyhing on other keyboard layouts (only tested german and US)

Send a PR to miniquad, there is now post-processing of js files in miniquad repo. I'll update the bundle on the next macroquad update :)

**Comment by FaunKr** [comment]
The same Problem exists for the "-"-key on the german keyboard, which return a constant "/". 
It can be fixed by a similiar way and still work with the us-layout afterwards.
