### ISSUE TITLE
srand() with get_time() gives always the same random sequence

### ISSUE THREAD

**Issue by fcoiffier** [not-fl3/macroquad#519]
If I initialize the random generator with: 
```rust
rand::srand(get_time() as u64);
```
it gives always the same sequence.

But if I initialize it with:
```rust
rand::srand(macroquad::miniquad::date::now() as _);
```
as seen in #369 the sequence is different at each run.

**Comment by not-fl3** [comment]
yes, `get_time` gives time since game start (https://docs.rs/macroquad/latest/macroquad/time/fn.get_time.html)
while `date::now` is a unix time, time since 1970
