### ISSUE TITLE
Troubles compiling for ios

### ISSUE THREAD

**Issue by shykeiichi** [not-fl3/macroquad#545]
When compiling a game i made for mobile using the x86_86-apple-ios build target on a mac pro 2017 i get a link error which reads:

`= note: Undefined symbols for architecture x86_64:

            "_AudioQueueAllocateBuffer", referenced from:

                quad_snd::snd::AudioContext::new::h7d3f904fb9710b8c in libquad_snd-09dd9deb410bf2d0.rlib(quad_snd-09dd9deb410bf2d0.quad_snd.79fc9eca-cgu.3.rcgu.o)

            "_AudioQueueEnqueueBuffer", referenced from:

                quad_snd::snd::saudio_coreaudio_callback::h1a9b06ed611dd0ae in libquad_snd-09dd9deb410bf2d0.rlib(quad_snd-09dd9deb410bf2d0.quad_snd.79fc9eca-cgu.3.rcgu.o)

                quad_snd::snd::AudioContext::new::h7d3f904fb9710b8c in libquad_snd-09dd9deb410bf2d0.rlib(quad_snd-09dd9deb410bf2d0.quad_snd.79fc9eca-cgu.3.rcgu.o)

            "_AudioQueueNewOutput", referenced from:

                quad_snd::snd::AudioContext::new::h7d3f904fb9710b8c in libquad_snd-09dd9deb410bf2d0.rlib(quad_snd-09dd9deb410bf2d0.quad_snd.79fc9eca-cgu.3.rcgu.o)

            "_AudioQueueStart", referenced from:

                quad_snd::snd::AudioContext::new::h7d3f904fb9710b8c in libquad_snd-09dd9deb410bf2d0.rlib(quad_snd-09dd9deb410bf2d0.quad_snd.79fc9eca-cgu.3.rcgu.o)

          ld: symbol(s) not found for architecture x86_64

          clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I think the error is withing libquad_snd but im not using any sound so im thinking if i could exclude libquad_snd from the compilation or if theres an easier fix.

**Comment by not-fl3** [comment]
Should be fixed now! 
`cargo update` should resolve it

**Comment by shykeiichi** [comment]
Works now thanks!
