### ISSUE TITLE
Is max log level supported?

### ISSUE THREAD

**Issue by chipsenkbeil** [not-fl3/macroquad#550]
Using macroquad 0.3.25, I'm leveraging the default logging implementation (not `log-rs`). I'm currently using `macroquad::logging::debug`, and want to disable those outputs, but I can't figure out where the minimum log level is configured.

It looks like the default imports `miniquad::{debug, error, info, trace, warn}`. When I skimmed miniquad, it looks like the conditionals that are used to check the max log level have been commented out, so does that mean log levels are not supported unless we switch to the `log-rs` feature?

With the `log-rs` feature, we still need to import the recommended logging crates to support wasm and desktop, right?

**Comment by not-fl3** [comment]
macroquad do not really provide any control over logs, if you want this control - yes, you need log-rs(or any other log's post-processor like a custom debug! macro)
