### ISSUE TITLE
Delete (Backspace) key on Mac (M1) glitches in editbox

### ISSUE THREAD

**Issue by sparshg** [not-fl3/macroquad#552]
Delete (backspace on PC) key seems glitchy on macos (M1 Air 2020) in editbox or input_text

It doesn't do anything on tap, but when held it inserts bunch of spaces and after 8 or so spaces, works normally, that means it erases those spaces and then the text as it should.

https://user-images.githubusercontent.com/43041139/211876746-d63beed6-4a7f-4d75-8083-2c0f647cc285.mov

**Comment by 107zxz** [comment]
Also happening on Intel Macbook Pro 2017 if it helps

**Comment by adambiltcliffe** [comment]
Same issue occurs on Windows. `git bisect` narrows it down to one of the following commits but I can't tell which because none of them will build now:

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
39588b8f13c3d0fcd8f8989d03939b63ef12693e
ab92087e9b4df4df5b69532e5c9d75a44c234d1a
a76a2dc001f1d752d5b0689c8382bfd54fcf69ea
c80ee2cd085fe653649787fae989dc3c1c57806a
5c91e6d785dcdc8058dec0e82811f8dfbe73951e
93625c5080427041b719a19eb7de7c34bec3538d
8438c76ac87c47e77a077b39f3d3cd6bd93eb104
f983a1ccd026adc7c3568272276b09d7345e9b13
4442d5828e8915dc32466bea8e01cfc51b835db1
5ccdd9a6a4631799841a18a74273ae5bddd4f2cd
c15235deb1cba1ca65fc9f6f58d36918ccd8048c
We cannot bisect more!
```

**Comment by adambiltcliffe** [comment]
More useful: bug is introduced somewhere here - https://github.com/not-fl3/macroquad/compare/b2a8f60..c15235d

There are a bunch of backend changes to QuadContext in here which could be relevant but I don't know enough about miniquad's internal workings to spot any likely culprits

**Comment by 107zxz** [comment]
This still happens on Mac as of commit 6ae3eba.

https://user-images.githubusercontent.com/55370376/219983404-03fc9735-34dc-4622-9421-d2d71cf88350.mov
