### ISSUE TITLE
Cargo build fails

### ISSUE THREAD

**Issue by nico-mayora** [not-fl3/macroquad#559]
# System information
rustc 1.65.0 (897e37553 2022-11-02)

[dependencies]
macroquad = "0.3"

# Issue
![image](https://user-images.githubusercontent.com/68969663/218613371-f8fdb0bc-dbf4-486b-9dbd-3f8393b6d077.png)

**Comment by not-fl3** [comment]
`0.3.7` is a really old version, I am not really sure why this error happens, but if using this exact version in not a requirement, I would recommend to just update (`cargo update`) t

**Comment by nico-mayora** [comment]
What version should I be using? I just copied the version in README.md:
![image](https://user-images.githubusercontent.com/68969663/218757304-be1d1405-c450-45e7-90fa-75af8124a7d4.png)

**Comment by nico-mayora** [comment]
Ah it seems, for whatever reason, cargo decided to install 0.3.7 on its own. After running `cargo update` it seems to be all right now. Thanks!
