### ISSUE TITLE
The main macro has no effect on the window

### ISSUE THREAD

**Issue by bhasim1** [not-fl3/macroquad#562]
Code to reproduce: 
```
use macroquad::prelude::*;

fn window_conf() -> Conf {
    return Conf {
        window_title: "test".to_string(),
        ..Default::default()
    };
}

#[macroquad::main("window_conf")]
async fn main() {
    println!("Hello World");
}
```
This code should give the window the title: "test" but it uses the fallback title that was given: "window_conf".

The winapi crate also prints an error, which I think is irrelevant, but I still want to mention it.

**Comment by not-fl3** [comment]
I believe `#[macroquad::main(window_conf)]` will do, like here: https://github.com/not-fl3/macroquad/blob/master/examples/window_conf.rs#L11

**Comment by bhasim1** [comment]
Yeah that works thx! I was just confused because of the docs https://docs.rs/macroquad/latest/macroquad/attr.main.html
