### ISSUE TITLE
Android build doesn't work

### ISSUE THREAD

**Issue by StormTrooper720** [not-fl3/macroquad#579]
I am making a game to learn about rust. I have made a simple game but would like to try to get it on my android phone. I followed the article on macroquad.rs using docker but when I run the second command, it gives an error. `error: '/opt/android-sdk-linux/platforms/android-29/android.jar' does not exist`. The file indeed doesn't exist, but I don't know how to fix this. I have also tried the second method but recieve java errors explaining how there is no such class when running `tools/bin/sdkmanager "platform-tools"`. I then proceeded to install android studio and downloaded the sdk and ndk from there but when building my game I receive `error: Unable to find ar at /home/stormtrooper720/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar`. The file indeed doesn't exist. I don't know how to fix this or what to do. I use Linux Mint 21.1 if that changes anything.

**Comment by not-fl3** [comment]
Ok, just to clarify:
if you clone macroquad and run `docker run 
  --rm 
  -v $(pwd):/root/src 
  -w /root/src 
  notfl3/cargo-apk cargo quad-apk build --release --example basic-shapes`
  
  you are getting 
`error: '/opt/android-sdk-linux/platforms/android-29/android.jar' does not exist` error?

**Comment by StormTrooper720** [comment]
I'm not getting the error when compiling the examples, just my code. I don't know why

**Comment by StormTrooper720** [comment]
After looking through the cargo.toml files of macroquad and my game, I found that my game was trying to use an older android sdk (version 29). Removing this fixed my issue.
