### ISSUE TITLE
Hi where can I find the documentation for macroquad?

### ISSUE THREAD

**Issue by Joe23232** [not-fl3/macroquad#58]
Hi where can I find the documentation for `macroquad`?

**Comment by not-fl3** [comment]
https://docs.rs/macroquad/0.3.0-alpha.9/macroquad/index.html is the only documentation we have

**Comment by Joe23232** [comment]
Thanks for the link, but I have a few questions in regards to the example provided in your link:

```rust
use macroquad::prelude::*;

#[macroquad::main("BasicShapes")]
async fn main() {
    loop {
        clear_background(RED);
 
        draw_line(40.0, 40.0, 100.0, 200.0, 15.0, BLUE);
        draw_rectangle(screen_width() / 2.0 - 60.0, 100.0, 120.0, 60.0, GREEN);
        draw_circle(screen_width() - 30.0, screen_height() - 30.0, 15.0, YELLOW);
        draw_text("HELLO", 20.0, 20.0, 20.0, DARKGRAY);
 
        next_frame().await
    }
}
```

`#[macroquad::main("BasicShapes")]` So what does this exactly do?

`async fn main() ` Before calling the main function, how come we have to add this `async` word and what does it do exactly?

`next_frame().await` I believe this updates everything on the frame, however, what does this `.await` word even mean?

**Comment by alekspickle** [comment]
@Joe23232 This is basic asyncronous syntax. If ytou are not familiar what this is, you can read about [asyncronous programming](https://en.wikipedia.org/wiki/Asynchrony_(computer_programming)) and if you want to know specifically in Rust, I suggest you chew on this [async release notes](https://areweasyncyet.rs/).

**Comment by Joe23232** [comment]
I see, thaknks
