### ISSUE TITLE
Wasm exports error with bevy_ecs

### ISSUE THREAD

**Issue by Weldify** [not-fl3/macroquad#592]
I'm using bevy_ecs for my game but wasm exports always produce the following error:
![image](https://user-images.githubusercontent.com/66477673/235279109-2c512b3b-9c6f-47a8-9868-baa9efafb5c6.png)
I have tried using both multi and single threaded bevy_ecs but it still errors

**Comment by not-fl3** [comment]
`__wbindgen` indicates wasm-bindgen in the dependencies. `wasm-bindgen` requires using third-party binary to post-process .wasm file. You can read more about this here: https://github.com/not-fl3/macroquad/issues/212#issuecomment-835276147
