### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by dm67x** [not-fl3/macroquad#617]
Hi, 

I want to build a sample example using macroquad with text rendering for Android I got an error when I click on the screen.

![image](https://github.com/not-fl3/macroquad/assets/1593334/92da3cba-22dd-4c58-b577-4c91eddab271)

I update the macroquad editbox.rs using my own fork to be able to build the application.
- https://github.com/not-fl3/macroquad/pull/616

Do you have any idea why it happening? Btw, nothing is shown on the screen 😞

**Comment by not-fl3** [comment]
Are you talking about macroquad's `ui` sample? I'll take a look!

**Comment by dm67x** [comment]
No I didn't use any idea the only thing I used was drawing a text.

**Comment by not-fl3** [comment]
Should be fixed in 0.4.1, feel free to reopen if it is not :)
