### ISSUE TITLE
is there a reason for max_vertices to be 10000? 

### ISSUE THREAD

**Issue by nowakf** [not-fl3/macroquad#622]
I was trying to render teapots, and I saw in the source (quad_gl.rs:623) that max_vertices is set to 10,000. Is this just an arbitrary number? I get that there should be some limit (gpu memory) but 10,000 seems like a very small number.

I set it to u16::MAX and I was clocking 60fps on my (old) x220. 

If 10,000 is a good number, It might be worth including a note in the docs that suggests splitting up larger meshes.

**Comment by not-fl3** [comment]
bigger max_vertices will lead into more memory used, and taken that
- macroquad is not really suited for 3d 
- and most common number of vertices is batching is about 100
10000 looks like a good compromise.
