### ISSUE TITLE
Sound memory leak

### ISSUE THREAD

**Issue by andreymal** [not-fl3/macroquad#628]
```rust
loop {
    load_sound("./sound.ogg").await?;
}
```

RAM is leaking.

Like with font atlas, I tried to implement `Drop` for `Sound`:

```rust
impl Drop for Sound {
    fn drop(&mut self) {
        if Arc::strong_count(&self.0) < 2 {
            self.0.delete(&get_context().audio_context.native_ctx);
        }
    }
}
```

and this fixed the leak (but I'm not sure if this solution is complete and/or correct because I don't even know why `Arc` is used here)

**Comment by not-fl3** [comment]
Hopefully fixed with #813
