### ISSUE TITLE
Wasmer, wasm3 not working with macroquad

### ISSUE THREAD

**Issue by mutkach** [not-fl3/macroquad#636]
WASM target not working on: 
* Arch linux, FreeBSD 13.0
* Version: 0.4

Steps to reproduce:
* open [basic-shapes](https://github.com/not-fl3/macroquad/blob/master/examples/basic_shapes.rs) example
* `cargo build --target wasm32-unknown-unknown`
* `wasmer target/wasm32-unknown-unknown/debug/macroquad-test.wasm`

Output:
```
error: Unable to instantiate the WebAssembly module
╰─▶ 1: Error while importing "env"."setup_canvas_size": unknown import. Expected Function(FunctionType { params: [I32], results: [] })
```

if run with wasm3's [wasm-run](https://github.com/wasm3/node-wasm-run):
`[runtime] Error: TypeError: WebAssembly.instantiate(): Import #0 module="env" error: module is not an object or function`

HTML works fine though...

There's a chance I'm doing something terribly wrong though bear with me, I'm new to this wasm thing.

**Comment by not-fl3** [comment]
Macroquad do not support wasm3/wasmer.
I am not quite sure if this would be even possible, but, anyway, this target is not on the roadmap and I do not think it would ever be implemented.
