### ISSUE TITLE
Errors in `mq_js_bundle.js`

### ISSUE THREAD

**Issue by albertsgarde** [not-fl3/macroquad#643]
I am trying to serve my project in a http-server, but instead get a black screen and a bunch of errors in the console.
I am running using the HTML file suggested by the readme, but I get a black screen and a series of errors in the console. I initially thought the error had something to do with my code, but the error comes from `mq_js_bundle.js` which is loaded before my wasm. I get the same errors in both Chrome and Firefox.

The HTML I use, taken directly from the readme:
```
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Title</title>
    <style>
        html,
        body,
        canvas {
            margin: 0px;
            padding: 0px;
            width: 100%;
            height: 100%;
            overflow: hidden;
            position: absolute;
            background: black;
            z-index: 0;
        }
    </style>
</head>

<body>
    <canvas id="glcanvas" tabindex='1'></canvas>
    <!-- Minified and statically hosted version of https://github.com/not-fl3/macroquad/blob/master/js/mq_js_bundle.js -->
    <script src="https://not-fl3.github.io/miniquad-samples/mq_js_bundle.js"></script>
    <script>load("target/wasm32-unknown-unknown/release/main.wasm");</script> <!-- Your compiled wasm file -->
</body>

</html>
```

The errors, copied from the Chrome console, but the same as those in Firefox:
```
No glGetString function in gl.js
add_missing_functions_stabs @ mq_js_bundle.js:3
(anonymous) @ mq_js_bundle.js:3
Promise.then (async)
load @ mq_js_bundle.js:3
(anonymous) @ (index):26
mq_js_bundle.js:3 No glGenerateMipmap function in gl.js
add_missing_functions_stabs @ mq_js_bundle.js:3
(anonymous) @ mq_js_bundle.js:3
Promise.then (async)
load @ mq_js_bundle.js:3
(anonymous) @ (index):26
mq_js_bundle.js:3 No __wbindgen_describe function in gl.js
add_missing_functions_stabs @ mq_js_bundle.js:3
(anonymous) @ mq_js_bundle.js:3
Promise.then (async)
load @ mq_js_bundle.js:3
(anonymous) @ (index):26
mq_js_bundle.js:3 No __wbindgen_throw function in gl.js
add_missing_functions_stabs @ mq_js_bundle.js:3
(anonymous) @ mq_js_bundle.js:3
Promise.then (async)
load @ mq_js_bundle.js:3
(anonymous) @ (index):26
mq_js_bundle.js:3 No __wbindgen_externref_table_grow function in gl.js
add_missing_functions_stabs @ mq_js_bundle.js:3
(anonymous) @ mq_js_bundle.js:3
Promise.then (async)
load @ mq_js_bundle.js:3
(anonymous) @ (index):26
mq_js_bundle.js:3 No __wbindgen_externref_table_set_null function in gl.js
add_missing_functions_stabs @ mq_js_bundle.js:3
(anonymous) @ mq_js_bundle.js:3
Promise.then (async)
load @ mq_js_bundle.js:3
(anonymous) @ (index):26
mq_js_bundle.js:3 WASM failed to load, probably incompatible gl.js version
(anonymous) @ mq_js_bundle.js:3
Promise.catch (async)
load @ mq_js_bundle.js:3
(anonymous) @ (index):26
mq_js_bundle.js:3 TypeError: WebAssembly.instantiate(): Import #91 module="__wbindgen_placeholder__" error: module is not an object or function
    at mq_js_bundle.js:3:8895
```

I am using version `0.4.2` of `macroquad` and am running Windows 10.
I've tested on Chrome 116.0.5845.180 and Firefox 117.0 and get the same errors on both.

**Comment by not-fl3** [comment]
> mq_js_bundle.js:3     GET http://localhost:4000/main.wasm 404 (Not Found)

Is this file really there? If you post http://localhost:4000/main.wasm to the browser nav bar - do you get the file?

**Comment by albertsgarde** [comment]
I posted the wrong errors. Oops. Should be fixed now

**Comment by albertsgarde** [comment]
No, I mean the issue text should be fixed. The problem very much still exists, I've just posted the right error messages

**Comment by not-fl3** [comment]
> __wbindgen_describe 

wasm-bindgen use their own custom third-party binaries to post-process .wasm files. Its quite complicated to set up and I never did it myself, but I've see people do it, for example: https://github.com/not-fl3/macroquad/issues/212#issuecomment-835276147

You can also search for "wbindgen" here on github issues, it was discusssed quite often.

**Comment by albertsgarde** [comment]
Do you have any idea as to why I need to do that when running my own .wasm and not when running examples? What kind of thing could cause this?
If I knew what was making my project different from the examples I could try to avoid it.

**Comment by not-fl3** [comment]
you use wasm-bindgen as a dependency (probably as a sub-dependency)

**Comment by albertsgarde** [comment]
I managed to figure out that it was the `getrandom` crate that needed `wasm-bindgen`. After I fixed up which features I required in my dependencies so `getrandom` was no longer a transitive dependency everything worked.
Thank you so much
