### ISSUE TITLE
WASM: Building via `--target web` causes an issue with `env` module

### ISSUE THREAD

**Issue by r0bertcode** [not-fl3/macroquad#651]
Hello,

I am having an issue porting my macroquad app into the browser via `wasm-pack`. 

When building for web via command:

```
wasm-pack build --target web
```
The first line of the JS file is:

```
import * as __wbg_star0 from 'env';
```

This leads to this error when loading the index.html and calling `init`:

```
Failed to resolve module specifier "env". Relative references must start with either "/", "./", or "../".
```

I read many other threads on this issue and tried to manually shim the compatibility, but to no avail. Is Macroquad not compatible with the target of web?

For context, the only deps I am using is:
```
[dependencies]
macroquad = "0.4.2"
rand = "0.8.5"
getrandom = { version = "0.2.10", features = ["js"] }
```

So, I am almost certain there is not a dep issue with `rand` or `getrandom`.

Any insight would be appreciated, thanks!

**Comment by not-fl3** [comment]
> __wbg_star0

One of your dependencies (getrandom) depends on wasm-bindgen. Setting up wasm-bindgen is complciated, you can read this comment for more information: https://github.com/not-fl3/macroquad/issues/212#issuecomment-835276147

Unfortunately I do not know much about wasm-pack to comment on this part, I guess it is possible to set it up with wasm-bindgen, but, again, I never did it, I personally just do not use depdendencies that require any third-party binaries to work.

**Comment by r0bertcode** [comment]
> > __wbg_star0
> 
> One of your dependencies (getrandom) depends on wasm-bindgen. Setting up wasm-bindgen is complciated, you can read this comment for more information: [#212 (comment)](https://github.com/not-fl3/macroquad/issues/212#issuecomment-835276147)
> 
> Unfortunately I do not know much about wasm-pack to comment on this part, I guess it is possible to set it up with wasm-bindgen, but, again, I never did it, I personally just do not use depdendencies that require any third-party binaries to work.

I went ahead and made a project with only macroquad as a dependency and tried to follow that posting and then also tried the updated script located here: https://gist.github.com/nobbele/0d932a993786ed081632254fb6b01e25 to no avail. 

I guess something has changed in the time from that posting. I will keep looking for a compatibility workaround and see if I can get it working.

**Comment by r0bertcode** [comment]
> > __wbg_star0
> 
> One of your dependencies (getrandom) depends on wasm-bindgen. Setting up wasm-bindgen is complciated, you can read this comment for more information: [#212 (comment)](https://github.com/not-fl3/macroquad/issues/212#issuecomment-835276147)
> 
> Unfortunately I do not know much about wasm-pack to comment on this part, I guess it is possible to set it up with wasm-bindgen, but, again, I never did it, I personally just do not use depdendencies that require any third-party binaries to work.

I have not been able to find a shim, but interested to know how are you porting the example WASM into `https://macroquad.rs/examples/`?

**Comment by not-fl3** [comment]
They are all built following [the instructions](https://github.com/not-fl3/macroquad#wasm). If this doesn't work on your machine on macroquad's examples - its a bug, feel free to open an issue!
