### ISSUE TITLE
Are max_vertices and max_indices changable somehow?

### ISSUE THREAD

**Issue by ryanpeach** [not-fl3/macroquad#657]
https://github.com/not-fl3/macroquad/blob/2d62c280e8828560a039c36c40e1a058fcc8e65c/src/quad_gl.rs#L631

This seems like a relatively low number. Also why are indices less than vertices, you usually need more.

Is there some reason for this?

**Comment by ryanpeach** [comment]
I see this issue https://github.com/not-fl3/macroquad/issues/622

But it just doesn't seem warranted that this isn't customizable based on the user preference.

**Comment by not-fl3** [comment]
> I see this issue #622
> 
> But it just doesn't seem warranted that this isn't customizable based on the user preference.

I still thing that current macroquad is fundamentally incompatible with any real 3d, so I don't believe that all the effort into making this customizable would be worth it

**Comment by ryanpeach** [comment]
So I just switched to ggez and just because you don't support 3d doesn't mean you don't support mesh's. My thing was a 2d mesh, much easier to draw in my case than a sprite. I notice that ggez actually makes 2d meshes their primary draw type, which is amazing! So just to say that meshing does not imply 3d, so making the library have good meshing is pretty important, especially for procedural stuff.
