### ISSUE TITLE
Initialize button with texture doesn't work

### ISSUE THREAD

**Issue by WindowGenerator** [not-fl3/macroquad#664]
I tried initialize button with png texture from example [ui](https://github.com/not-fl3/macroquad/blob/master/examples/ui.rs), but this [place](https://github.com/not-fl3/macroquad/blob/master/examples/ui.rs#L209) in the example doesn't work. Below I compared last worked version with latest.

macroquad=0.3.26
![image](https://github.com/not-fl3/macroquad/assets/41333030/f9064e25-d1d5-49f0-9acf-dea8b3b13f30)

macroquad=0.4.4
![image](https://github.com/not-fl3/macroquad/assets/41333030/574caf9f-c2c3-4476-bcb5-ace4f3fa7121)

OS:
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
```

**Comment by streak324** [comment]
https://github.com/not-fl3/macroquad/blob/8f2856f09674324b1222d7f344b2d101377430bb/src/ui/render/mesh_rasterizer.rs#L250-L253

removing this if check gets the textures showing again. however I'm not sure what unintended behavior would result from the check being removed.
