### ISSUE TITLE
3D Example Segmentation fault on Linux

### ISSUE THREAD

**Issue by LaineZ** [not-fl3/macroquad#67]
I cloned repository and tried run 3d example with command: 

```cargo run --example 3d --release```

After compile I got this error:

```
GLX: failed to create GL context
Segmentation fault (core dumped)
```

glxinfo render:
```
OpenGL vendor string: X.Org R300 Project
OpenGL renderer string: ATI RS480
OpenGL version string: 2.1 Mesa 20.0.8
OpenGL shading language version string: 1.20
```

**Comment by not-fl3** [comment]
Unfortunately, the minimal OpenGL version supported is 3.2 :(
