### ISSUE TITLE
`choose` should never return `None` if the Vec has an element

### ISSUE THREAD

**Issue by Bytekeeper** [not-fl3/macroquad#690]
This little test will fail (most of the times):
```Rust
    let test = vec![1];
    for _ in 0..1000000000 {
        assert!(test.choose().is_some());
    }
```
The reason is: `choose() ` uses `gen_range(0, test.len())` which is wrong - as `gen_range` includes both ends and can return 1 here.

**Comment by not-fl3** [comment]
Looks like an error, feel free to submit a PR!

**Comment by Bytekeeper** [comment]
This is related to not-fl3/quad-rand#12 
The bug is not present on master because the last commit fixed it. But the released version has the bug. More info in the linked issue.
