### ISSUE TITLE
Add ability to run custom code before async main and opening a window

### ISSUE THREAD

**Issue by Shelim** [not-fl3/macroquad#707]
Is there a way to run a custom code before starting async main and opening a window? I checked up documentation and I was unable to find one.

Even a simple callback in the structure passed to macro would be sufficient.

**Comment by not-fl3** [comment]
sure, you can call macroquad::start without a macro and call any custom code before this call

**Comment by Shelim** [comment]
For anyone coming here from Google, here is a full solution (uses undocumented function `from_config`):

```rust
fn main() {
    // Do anything
    let conf = Conf {
        // Put anything you want
        ..Default::default()
    }
    macroquad::Window::from_config(conf, main_loop());
}

async fn main_loop() {
    loop {
        clear_background(BLACK);
        next_frame().await
    }
}
```
