### ISSUE TITLE
`mouse_delta_position` always returns zero when called multiple times in a frame

### ISSUE THREAD

**Issue by elgan65536** [not-fl3/macroquad#717]
The following code demonstrates this bug:
```rust
use macroquad::prelude::*;
#[macroquad::main("game")]
async fn main() {
    loop {
        clear_background(BLACK);
        let Vec2 { x: x1, y: y1 } = mouse_delta_position();
        let Vec2 { x: x2, y: y2 } = mouse_delta_position();
        draw_text(&format!("x1: {x1:.2}, y1: {y1:.2}"), 30., 30., 30., WHITE);
        draw_text(&format!("x2: {x2:.2}, y2: {y2:.2}"), 30., 60., 30., WHITE);
        next_frame().await
    }
}
```
x1 and y1 correctly represent the mouse movement but x2 and y2 are always zero.

**Comment by typio** [comment]
That's the intended behavior, if you look at the source code for `mouse_delta_position` it sets previous stored mouse position to the current mouse position, so it is ready to measure the distance on the next frame. The function isn't side-effect free.

https://docs.rs/macroquad/latest/src/macroquad/input.rs.html#68-81
