### ISSUE TITLE
Flickering issue

### ISSUE THREAD

**Issue by AnkurMal** [not-fl3/macroquad#722]
I don't know why, but the window is flickering a lot. I have Windows 11, and 'high_dpi' is set to true.

**Comment by not-fl3** [comment]
Any additional info?
Does it flicker on the `basic_shapes` example? What OS and macroquad version do you use?

**Comment by AnkurMal** [comment]
Hello, yes it did flicker on the basic_shapes example. Point no note, sometimes it flickers too frequently, but sometimes it doesn't at all. I am using Windows 11 and macroquad version is 0.4.5
