### ISSUE TITLE
Asynchronous font loading

### ISSUE THREAD

**Issue by davawen** [not-fl3/macroquad#729]
Hi!
Is there any way to load a font asynchronously?

Right now, loading a single font can cause up to a few seconds of startup delay, which isn't acceptable with the application I'm developing.  
I've tried offloading the font loading to another thread, but alas it requires being loaded from the main thread (which is understandable).

I'm guessing most of the time is spent populating the font cache in [https://docs.rs/macroquad/0.4.7/src/macroquad/text.rs.html#270-281](`load_ttf_font_from_bytes`), but unfortunately I can't find a way to manually create the font on my own to do it incrementally.

Any ideas?
Thank you!

**Comment by not-fl3** [comment]
I am not sure if this is possible, but just to double check - is it a few seconds in a release build?

**Comment by davawen** [comment]
Argh! I forgot to run it in release mode... My bad...  
It loads a lot faster when running it with the appropriate flag :smile:

Although, it might still be interesting to expose a way to create a font without it automatically populating the font cache.  If you need to load a lot of fonts, it can add up pretty quickly.
Anyways, sorry for the stupid issue, and thank you for your work on macroquad!
