### ISSUE TITLE
bumpalo dependence (android)

### ISSUE THREAD

**Issue by vada4367** [not-fl3/macroquad#730]
In docker image cargo:

error: package `bumpalo v3.16.0` cannot be built because it requires rustc 1.73.0 or newer, while the currently active rustc version is 1.71.1

I think you should just update cargo | cargo-quad in image
Please fix))

**Comment by AdamSlayer** [comment]
I have the same issue.
You can add `bumpalo = "= 3.4"` to your `Cargo.toml` to force older bumpalo version as a temporary fix.

**Comment by vada4367** [comment]
Thanks!
