### ISSUE TITLE
How to turn off vsync?

### ISSUE THREAD

**Issue by YuichiKamishiro** [not-fl3/macroquad#755]
My fps cant go above 60.

**Comment by Ztry8** [comment]
https://github.com/not-fl3/macroquad/issues/360

> Unfortunately this is not possible :(
> 
> On web browser will send animationFrame as fast as it feels doing so - depending on other tabs activity and so on.
> On PC vsync usually depends on the driver settings.

**Comment by Ztry8** [comment]
Macroquad will limit your fps to only 60, on any platform, on any hardware.

**Comment by not-fl3** [comment]
Just for someone who will come here from google :) 

Macroquad do not limit fps, it is not doing anything with fps at all. Some platforms (browsers in particular) gives us no control over fps, some - give siomecontrol over vsync, but it can be overriten by the user in the driver settings (windows), with env variable(linux) and, I guess, performance/battery saving settings (android/ios). 

`swap_interval : Some(0)` in Conf might be a solution, but it does not guarantee a disbled vsync, it really is super platform specific and there are varios way user can enable/disable vsync. 
 https://docs.rs/miniquad/latest/miniquad/conf/struct.Platform.html#structfield.swap_interval

**Comment by GustavoRamos112** [comment]
````rust
use macroquad::prelude::*;

fn window_conf() -> Conf {
    Conf {
        window_title: "Uncap fps".to_owned(),
        sample_count: 0,
        platform: miniquad::conf::Platform {
          swap_interval: Some(0), // <- this line: 0: unlimited fps, 1: 60 fps, 2: 30 fps, 3: 15 fps
          ..Default::default()
        },
        window_resizable: true,
        window_width: 800,
        window_height: 600,
        ..Default::default()
    }
}

#[macroquad::main(window_conf)]
async fn main() {
  //? main loop
  loop {
    clear_background(BLACK);

    draw_text(
      format!("{:.4} s/{:.0} fps", get_frame_time(), 1.0/(get_frame_time() as f32)).as_str(), 
      0.0, 13.0, 20.0, WHITE,
    );

    next_frame().await
  }
}
````
