### ISSUE TITLE
package `bumpalo v3.16.0` cannot be built because it requires rustc 1.73.0 or newer

### ISSUE THREAD

**Issue by historydev** [not-fl3/macroquad#763]
Hello, my system:
OS: win11 x86_64
docker os:
```
[root@9e223649fee1 src]# uname -a
Linux 9e223649fee1 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux

```

I tried to build the application using these instructions:
https://macroquad.rs/articles/android/

I downloaded the image, ran the command, and at the end of a very long (700kb/s) download of packages, I received the error:
```
error: package `bumpalo v3.16.0` cannot be built because it requires rustc 1.73.0 or newer, while the currently active rustc version is 1.71.1
```
I went ahead and tried to update rustc, but apparently this is not possible for this particular system.
Tried:
```
rustup update
rustup remove rustc-xxxxxxx
rustup add rustc-xxxxxxxx
```
Next, I tried to add the bumpalo package of the version below via cargo add, but it didn’t work, as I understand, I’m still new to growth and have not yet managed to fully cover cli cargo.

The error remained after:
```
[root@9e223649fee1 src]# cargo add bumpalo@3.15.1
 Updating crates.io index
 Adding bumpalo v3.15.1 to dependencies.
 Features:
 -allocator-api2
 - allocator_api
 - boxed
 - collections
 -std

```

Other cargo-quad-apk commands also give the same error:
```
cargo-quad-apk build/install/run
```

I also tried to completely remove the rast via rustup, but after installation, a bunch of android files like N.jar were missing.

So far I have not tried to build my docker image from the Android sdk/ndk, but if my problem can only be solved by manual installation, I will do it.

What else should I try?

**Comment by not-fl3** [comment]
hmm, what error rustup update give?

**Comment by historydev** [comment]
> hmm, what error rustup update give?
> 
> edit: Pushing an updated container with 1.79 right now, but it will take a while. Usually `rustup update` inside the container is the easiest workaround, feel free to post an error of what went wrong, its concerning that it doesnt't work anymore

The Rustup update did not produce any errors, but also did not detect a version of rustc-xxxxx older than 1.71, now I can’t find the updated container, apparently it has not yet been validated or whatever the processes are, if there is a Docker file, I can build it.

**Comment by not-fl3** [comment]
sure, thats the Dockerfile: https://github.com/not-fl3/cargo-quad-apk/blob/master/Dockerfile

btw `notfl3/cargo-apk` is updated, now it should have 1.79, `docker update notfl3/cargo-apk` might be a solution

**Comment by historydev** [comment]
> sure, thats the Dockerfile: https://github.com/not-fl3/cargo-quad-apk/blob/master/Dockerfile
> 
> btw `notfl3/cargo-apk` is updated, now it should have 1.79, `docker update notfl3/cargo-apk` might be a solution

Cargo.toml (for first try in android_v and sdk_v i set 30):
```
[package.metadata.android]
package_name = "org.example.your_project_name"
android_version = 29
target_sdk_version = 29
min_sdk_version = 26
```

```
PS G:\Desktop\macroquad_learn> docker run --rm -v G:\Desktop\macroquad_learn:/root/src -w /root/src notfl3/cargo-apk cargo quad-apk build --release
error: '/opt/android-sdk-linux/platforms/android-30/android.jar' does not exist
PS G:\Desktop\macroquad_learn> docker run --rm -v G:\Desktop\macroquad_learn:/root/src -w /root/src notfl3/cargo-apk cargo quad-apk build --release
error: '/opt/android-sdk-linux/platforms/android-29/android.jar' does not exist

```

**Comment by historydev** [comment]
> sure, thats the Dockerfile: https://github.com/not-fl3/cargo-quad-apk/blob/master/Dockerfile
> 
> btw `notfl3/cargo-apk` is updated, now it should have 1.79, `docker update notfl3/cargo-apk` might be a solution

I build image locally from repo and got this error again:
```
=> exporting to image                                                                                                                                                                                                                                                                                         2.4s 
 => => exporting layers                                                                                                                                                                                                                                                                                        2.4s 
 => => writing image sha256:bf5fd089440920d08644997f9ca9611268395ae8a10b572ea                                                                                                                                                                                                                   0.0s 
 => => naming to docker.io/library/cargo-quad                                                                                                                                                                                                                                                                  0.0s 

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview
PS G:\Desktop\macroquad_learn\cargo-quad-apk> docker images
REPOSITORY         TAG       IMAGE ID       CREATED          SIZE
cargo-quad         latest    bf5fd0894409   14 seconds ago   6.76GB
notfl3/cargo-apk   latest    90b79eb6b183   11 hours ago     6.38GB
PS G:\Desktop\macroquad_learn\cargo-quad-apk> docker run --rm -v G:\Desktop\macroquad_learn:/root/src -w /root/src cargo-quad cargo quad-apk build --release      
error: '/opt/android-sdk-linux/platforms/android-29/android.jar' does not exist

```

**Comment by not-fl3** [comment]
> android_version = 29
> target_sdk_version = 29
> min_sdk_version = 26

Same, android_version = 29 gives me the same error! 
But I am not sure if it should work, isn't `target_sdk_version` a SDK version used to develop the app, not he minimal sdk version required to run the app?

**Comment by historydev** [comment]
> > android_version = 29 
> > target_sdk_version = 29 
> > min_sdk_version = 26
> 
> То же самое, target_sdk_version = 29 дает мне ту же ошибку! Но я не уверен, должно ли это работать, разве `target_sdk_version`версия SDK не используется для разработки приложения, а не минимальная версия SDK, необходимая для запуска приложения?

In fact, changing sdk-target/min-sdk did not change the android version, it was android_version that changed it.

I tried all the archives from https://macroquad.rs/articles/android/, this file is not there and it seems it never was. (`bin\arm-linux-androideabi-ar.exe`)

I'm looking for a way to assemble it or download it from where, I don't know what to do anymore..

![image](https://github.com/user-attachments/assets/34f2b6ce-2e48-4dd8-a0a0-43447f6281bf)

**Comment by historydev** [comment]
> > android_version = 29
> > target_sdk_version = 29
> > min_sdk_version = 26
> 
> Same, target_sdk_version = 29 gives me the same error! But I am not sure if it should work, isn't `target_sdk_version` a SDK version used to develop the app, not he minimal sdk version required to run the app?



In fact, changing sdk-target/min-sdk did not change the android version, it was android_version that changed it.

I tried all the archives from https://macroquad.rs/articles/android/, this file is not there and it seems it never was. (`bin\arm-linux-androideabi-ar.exe`)

I'm looking for a way to assemble it or download it from where, I don't know what to do anymore..

![image](https://github.com/user-attachments/assets/34f2b6ce-2e48-4dd8-a0a0-43447f6281bf)

**Comment by historydev** [comment]
https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html

```
cd ${NDK_HOME}/build/tools
mkdir NDK
python make_standalone_toolchain.py --api 30 --arch arm64 --install-dir NDK/arm64
```

Got:
```
PS D:\AndroidSDK\ndk\27.0.12077973\build\tools> python make_standalone_toolchain.py --api 30 --arch arm64 --install-dir NDK\arm64           
WARNING:__main__:THIS TOOL IS OBSOLETE. The %NDK%\toolchains\llvm\prebuilt\windows-x86_64\bin directory contains
target-specific scripts that perform the same task. For example,
instead of:

    C:\>python %NDK%\build\tools\make_standalone_toolchain.py \
        --arch arm64 --api 30 --install-dir toolchain
    C:\>toolchain\bin\clang++ src.cpp

Instead use:

    C:\>%NDK%\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android30-clang++ src.cpp

See https://developer.android.com/ndk/guides/other_build_systems for more
details.

```

Because my analysis led to exactly this, the error is in it, namely, quad-apk or cargo-apk executes `python %NDK%\build\tools\make_standalone_toolchain.py\
 --arch arm64 --api 30 --install-dir toolchain`, because the command is outdated, we do not receive the file `\bin\arm-linux-androideabi-ar.exe` and as a result we receive an error that it does not exist.

**Comment by not-fl3** [comment]
Just to separate two issues :) 

This one is about rust version in the docker container, is it fixed or is there anything I can do to fix it?

**Comment by historydev** [comment]
> Просто чтобы разделить два вопроса :)
> 
> Речь идет о версии Rust в контейнере Docker. Исправлена ​​ли она или можно ли что-то сделать, чтобы ее исправить?

No, none of the assembly methods work.

**Comment by not-fl3** [comment]
You still got that bumpalo error, the rust 1.73 one?

**Comment by historydev** [comment]
> У вас все еще есть эта ошибка Bumpalo, Rust 1.73?

https://github.com/not-fl3/macroquad/issues/763#issuecomment-2241463570

**Comment by not-fl3** [comment]
Ok, I am a bit lost now :) 

You do not have 
```
    android_version = 29
    target_sdk_version = 29
```

But you still get the android.jar issue? 

In other words, if you clone macroquad repo, run `docker run  --rm -v /tmp/registry:/usr/local/cargo/registry -v $(pwd):/root/src -w /root/src notfl3/cargo-apk cargo quad-apk build --example basic_shapes`, you get this error you posted?

(using default macroquad just to have something I can reproduce locally)

**Comment by historydev** [comment]
> Ok, I am a bit lost now :)
> 
> You do not have
> 
> ```
>     android_version = 29
>     target_sdk_version = 29
> ```
> 
> But you still get the android.jar issue?
> 
> In other words, if you clone macroquad repo, run `docker run --rm -v /tmp/registry:/usr/local/cargo/registry -v $(pwd):/root/src -w /root/src notfl3/cargo-apk cargo quad-apk build --example basic_shapes`, you get this error you posted?
> 
> (using default macroquad just to have something I can reproduce locally)

Yes, that's right, this error occurs whenever you use docker pull notfl3/cargo-apk, or build directly from the repository:

```
Digest: sha256:6b70dabc44ef283b9533ff5f49ccd246579ee1b4204691bf5ab322c5846dbc0b
Status: Downloaded newer image for notfl3/cargo-apk:latest
docker.io/notfl3/cargo-apk:latest

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview notfl3/cargo-apk
PS G:\Desktop\macroquad_learn> docker run --rm -v G:\Desktop\macroquad_learn:/root/src -w /root/src notfl3/cargo-apk cargo quad-apk build --example basic_shapes
error: '/opt/android-sdk-linux/platforms/android-30/android.jar' does not exist
PS G:\Desktop\macroquad_learn> 

```

**Comment by not-fl3** [comment]
Unfortunately I can't reproduce it :(
I would double check that there is nothing about version = 30 anywhere in Cargo.toml, do a fresh repo clone, double check that there are no local changes etc. 

But it might be some obscure bug, let's keep it open!

**Comment by historydev** [comment]
> К сожалению, я не могу это воспроизвести :( Я бы еще раз проверил, что нигде в Cargo.toml нет ничего о версии = 30, сделал бы свежий клон репозитория, еще раз проверил бы, что нет локальных изменений и т. д.
> 
> Но это может быть какой-то неизвестный баг, давайте оставим это открытым!

Sorry, at first I didn’t understand what exactly I needed to do, I cloned the repository and ran the command - the example compiled.

But why doesn't my project compile, possibly due to third-party dependencies?

```
[package]
name = "macroquad_learn"
version = "0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4"
tokio = "1.38.1"
time = "0.3.36"
rand = "0.8.5"

[package.metadata.android]
package_name = "org.example.your_project_name"
android_version=30
target_sdk_version = 30
min_sdk_version = 16
```

**Comment by historydev** [comment]
And so, I understand that the problem is in Cargo.toml, namely in the android version, I installed 31 and the assembly started, that is, I can only build for a certain version of android and the application will not work on the rest?

```
[package]
name = "macroquad_learn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4"
#tokio = "1.38.1"
#time = "0.3.36"
#rand = "0.8.5"
#
[package.metadata.android]
package_name = "org.example.your_project_name"
android_version = 31
target_sdk_version = 28
min_sdk_version = 16
```
