### ISSUE TITLE
Memory leak in a very basic main loop?

### ISSUE THREAD

**Issue by ferama** [not-fl3/macroquad#782]
I experienced the issue building a basic main loop on apple M1 (can't actually test it on other platforms)

# How to reproduce

Create a project and add the "memory-stats" dep (https://docs.rs/memory-stats/latest/memory_stats/)
Create a very basic loop like the following:

```rust
use macroquad::prelude::*;
use memory_stats::memory_stats;

#[macroquad::main("leak")]
async fn main() {
    loop {
        if let Some(usage) = memory_stats() {
            draw_text(
                format!("mem: {}", usage.physical_mem).as_str(),
                10., 
                20., 
                25.0, 
                WHITE
            );
        }

        next_frame().await
    }
}
```

Start generating input events over the main window (move the mouse pointer, press some buttons etc)
You can observe the memory counter increase and never go down. You can obviously observe the same behaviour without
the memory_stats() part and looking at operating system process monitor.

I'm doing something wrong?
Perhaps is an issue on M1 only?

I will test on other hardware as soon as I can put my hands on it, but it's weird anyway.

**Comment by KamilM1205** [comment]
Same here. I only draw some ui and nothing. After that my app starts use over than 1GB RAM.
Platform: Windows 10 x64
Macroquad version 0.4.12
Rust ver. 1.80.1 stable

**Comment by ferama** [comment]
I did some more in-depth test and it seems it takes a while but at the end the memory goes down. Sometimes it starts from 50M goes up until about 200M e then starts to stabilize and eventually to drop.

**Comment by ferama** [comment]
After 2 weeks of developing with macroquad I think I can safely say that we can close this :)
