### ISSUE TITLE
Camera3D's Fov description is misleading.

### ISSUE THREAD

**Issue by tynberry** [not-fl3/macroquad#783]
When looking at the Camera's 3D description of field `fovy`, it is stated that it is in degrees. [docs link](https://docs.rs/macroquad/0.4.12/macroquad/camera/struct.Camera3D.html#structfield.fovy)
However in [source](https://github.com/not-fl3/macroquad/blob/f77e656c811d51140f27da778917cf368c881605/src/camera.rs#L214), it is passed unchanged into a function, which expects fovy in radians. [link](https://github.com/EmbarkStudios/glam-rs/blob/ecf3904b2fb639a979127f457b259f4b83b0340b/src/core/traits/projection.rs#L11)

This is for version macroquad=0.4.12.

**Comment by not-fl3** [comment]
Thanks for report, feel free to make a doc comment PR!

**Comment by tynberry** [comment]
PR #785
