### ISSUE TITLE
How to pass an array of elements to a shader?

### ISSUE THREAD

**Issue by historydev** [not-fl3/macroquad#821]
How to pass an array of elements to a shader?

I use https://docs.rs/macroquad/latest/macroquad/prelude/struct.UniformDesc.html

Namely ```UniformDesc::array(...)```

When trying to set a uniform of the array type, it says that this operation is not supported.

```set_uniform do not support uniform arrays```

Since the number of shaders is limited, one shader needs to be bound to N elements and I need to pass quite a lot of parameters for each object and there are also a lot of objects themselves (10,000 or more), manually writing something is not an option at all.

Please tell me what I should do?

**Comment by not-fl3** [comment]
this example might be relevant: https://github.com/not-fl3/macroquad/blob/master/examples/custom_material.rs#L95

**Comment by historydev** [comment]
> this example might be relevant: https://github.com/not-fl3/macroquad/blob/master/examples/custom_material.rs#L95

Thank you, I'll try, it will take a little time to answer

**Comment by historydev** [comment]
> this example might be relevant: https://github.com/not-fl3/macroquad/blob/master/examples/custom_material.rs#L95

I have another unrelated question, if you don't mind answering.

Where can I learn glsl completely?

Because I'm almost blind, I couldn't find anything useful in the khronos documentation except for data types.

I'm using version 300 es, but I couldn't find any trivial global outputs and inputs like gl_Position or FragColor, all this was suggested to me by gpt ..

Because of this, I experience huge wastes of time on selecting values ​​by trial and error and I don't like it at all.
