### ISSUE TITLE
Where are all the uniforms submitted to glsl documented?

### ISSUE THREAD

**Issue by historydev** [not-fl3/macroquad#836]
Like Projection, Model?
https://docs.rs/macroquad/latest/src/macroquad/quad_gl.rs.html#1100-1106

**Comment by not-fl3** [comment]
I don't think it is properly documented anywhere, but those Projection Model and Time are pretty much it, no other embedded uniforms

**Comment by historydev** [comment]
> I don't think it is properly documented anywhere, but those Projection Model and Time are pretty much it, no other embedded uniforms

`_Time` its `get_time()` or `get_frame_time()`?

**Comment by Rushmore75** [comment]
https://docs.rs/macroquad/latest/src/macroquad/quad_gl.rs.html#704

(in case any other people come across this issue)
