### ISSUE TITLE
Why does gen_range() always return the same result?

### ISSUE THREAD

**Issue by historydev** [not-fl3/macroquad#837]
I decided to debug a little and discovered the fact that the program seems to remember the last call and works from it.

If there was no call, I always get the minimum value on the first call.

```
#[macroquad::main(window_config)]
async fn main() {

    // If cycle uncomment hue always: 184.60123, else otherwise always 0
    for _ in 0..100 {
        let hue = gen_range(1., 360.); 
        println!("{hue}");
    }

    let hue = gen_range(0., 360.);
    println!("Hue: {hue}");
    
    loop { /* ... */ }
}
```

**Comment by not-fl3** [comment]
you might want to seed it with current time, `rand::srand(macroquq::miniquad::date::now() as _)` or something like this

**Comment by historydev** [comment]
> rand::srand(macroquq::miniquad::date::now() as _)

thx u
