### ISSUE TITLE
Is there a way to disable vsync?

### ISSUE THREAD

**Issue by historydev** [not-fl3/macroquad#839]
With nvidia vsync set as "application controlled", the fps does not cross the monitor's hertz.

However, if I turn it off, I get several thousand frames.

**Comment by Ztry8** [comment]
https://github.com/not-fl3/macroquad/issues/749#issuecomment-2365023583

**Comment by historydev** [comment]
> [#749 (comment)](https://github.com/not-fl3/macroquad/issues/749#issuecomment-2365023583)

thx u
