### ISSUE TITLE
Question: Custom Geometry Rendering

### ISSUE THREAD

**Issue by Pebaz** [not-fl3/macroquad#92]
Can an example be created or could someone point me in the right direction to be able to render a list of vertices/texcoords without a custom pipeline/shader? I'd like to use it like the other `draw_...()` functions if possible.

The goal here being to generate geometry in-game and then render it, but I don't need anything fancy (just textures).

**Comment by not-fl3** [comment]
Hi! 
Just merged a PR with models::draw_mesh function, take a look! :)

**Comment by Pebaz** [comment]
This is perfect! Thank you!
You're a ninja 🥷
